### ISSUE TITLE
Add a display rows per page dropdown or textbox with pagination

### ISSUE THREAD

**Issue by Muhammad-Arsalan31** [icflorescu/mantine-datatable#100]
**Is your feature request related to a problem? Please describe.**
It would be nice to add a dropdown to select how many rows user wants to show per page like this
![image](https://user-images.githubusercontent.com/31656210/196934525-14d47bf1-5788-462b-8296-d6074df48d9c.png)

**Describe the solution you'd like**
I think the prop recordPerPage should show the dropdown so that both dropdown and page info can be sync

**Describe alternatives you've considered**
An alternative can be to add a withLimitDropdown prop to table which if it is true it should show the limit dropdown and get the value from recordsPerPage state

```
<DataTable
  recordsPerPage="10"
  withLimitDropdown
/>
 ```

**Comment by icflorescu** [comment]
P.S. If someone else is willing to pick it up, please make sure to adjust the example page accordingly. It's not a feature if it's not documented and people don't know about it :-).

**Comment by icflorescu** [comment]
Overall, it shouldn't be difficult to implement. PRs are welcomed :-).

**Comment by Muhammad-Arsalan31** [comment]
I can work on this next week (because I am not free this weekend) I just want to know how are theses name of props are fine?

`onPageChange`, 
`recordsPerPageSizes` or `recordsPerPageOptions`
`recordsPerPageSelectLabel`

**Comment by icflorescu** [comment]
Let's stick with:

`onRecordsPerPageChange: (number) => void`
`recordsPerPageOptions: number[]`
`recordsPerPageLabel: string, defaulting to 'Records per page'`

This first one has to be in line with the already existing `recordsPerPage` property.

**Comment by Muhammad-Arsalan31** [comment]
Hi, I have worked on the feature and named the props as you mentioned above. but datatatypes are different for `onRecordsPerPageChange` and `recordsPerPageOptions` they are

`onRecordsPerPageChange: ((value: string | null) => void) | undefined;`
`recordsPerPageOptions: string[];`

the reason for this is that the select component takes values as a string array
```
   <Select
      onChange={onPerPageOptionChange}
      value={`${recordsPerPage}`}
      size={paginationSize}
      data={recordsPerPageOptions as (string | SelectItem)[]}
      sx={{ width: '80px' }}
   />
```

also  I am getting a typescript  error if I don't pass these props to datatable component. I have made them optional bt I don't know what this error is occurring can you help me on this

```
Type '{ withBorder: true; records: { id: string; firstName: string; lastName: string; email: string; birthDate: string;
 departmentId: string; }[]; columns: ({ accessor: string; width: number; } | { accessor: string; width: string; } | 
{ ...; })[]; ... 4 more ...; paginationColor: "ffaa11"; }' is not assignable to type 'IntrinsicAttributes & 
DataTableProps<{ id: string; firstName: string; lastName: string; email: string; birthDate: string; 
departmentId: string; }>'.
Translation: I was expecting a type matching A, but instead you passed B.
```

theses are some issue I am facing I can submit PR if I can fix this 

also the Ui is like this

![image](https://user-images.githubusercontent.com/31656210/197468901-12d3a017-0f7f-4f9f-9710-24bbe1cd7216.png)

**Comment by Muhammad-Arsalan31** [comment]
Hi @icflorescu o, do you have any suggestions to fix the issues so I can submit the PR

**Comment by icflorescu** [comment]
> data types are different for onRecordsPerPageChange and recordsPerPageOptions
You could convert them to numbers, because users will expect to be able to pass in numbers.

Regarding the TS error, I'm afraid I don't have enough information to understand where it comes from.

**Comment by icflorescu** [comment]
This should work in `v1.7.13` 🎉
