### ISSUE TITLE
Allow some rows not be selected

### ISSUE THREAD

**Issue by raikasdev** [icflorescu/mantine-datatable#101]
**Is your feature request related to a problem? Please describe.**
Set some rows to not be selectable like on MUI-datatables https://github.com/gregnb/mui-datatables/issues/172

**Describe the solution you'd like**
Similar to mui-datatables, function that checks if you can select the row. On those rows show a disabled checkbox

**Additional context**
https://github.com/gregnb/mui-datatables/issues/172

**Comment by icflorescu** [comment]
Sounds useful, thanks for the suggestion.
I'll do it at some point next week.

**Comment by icflorescu** [comment]
Implemented in `v.1.7.11`.
You can now provide a property called `isRecordSelectable` with type: `(record: T, index: number) => boolean`.
See the **Disable selection of certain records** section on the [records selection example page](https://icflorescu.github.io/mantine-datatable/examples/records-selection).
