### ISSUE TITLE
don't override paginationTextValue if provided

### ISSUE THREAD

**Issue by lssjbrolli** [icflorescu/mantine-datatable#102]
**Describe the bug**
 My custom paginationTextValue gets overridden if totalRecords is 0

**To Reproduce**
Add a custom paginationTextValue
remove all items
with no items paginationTextValue gets replaced with ...

**Comment by icflorescu** [comment]
Thanks!
This is now fixed in `v.1.7.10`.

**Comment by icflorescu** [comment]
One more thing: you can now customize the `loadingText` if you're not happy with the default `...`.
