### ISSUE TITLE
Drag & Drop row reorder

### ISSUE THREAD

**Issue by gfazioli** [icflorescu/mantine-datatable#107]
I was wondering how to implement a sort of drag & drop reorder for the data table rows.
Did you already plan anything about that?

**Comment by icflorescu** [comment]
This has been discussed before (see https://github.com/icflorescu/mantine-datatable/discussions/89) and TBH I'm not sure if/how this could be implemented to work with the already existent feature set.

**Comment by otobot1** [comment]
@gfazioli I posted an idea in #89. Take a look if you're interested.
