### ISSUE TITLE
Text size inside render prop seems to be ignored

### ISSUE THREAD

**Issue by OSiG43** [icflorescu/mantine-datatable#108]
**Describe the bug**
Text rendered in the render section of a column does not apply automatic line break

![image](https://user-images.githubusercontent.com/25371937/198687758-df44bc3a-195a-46c4-8b94-06a31665031a.png)

**Code**
```js
<DataTable
            striped
            highlightOnHover
            records={sortedData}
            columns={[
                {accessor: "customAccessor",
                    title:"Name",
                    render: (record)=>(<Text style={{width:70}}> {record.titre}</Text>),
                    width:300,
                    ellipsis:true
                },
                {accessor: "description",
                    title:"Description",
                    ellipsis:true
                },
            ]}
        >

> 
```

**Expected behavior**
the text should automatically go to the line when it exceeds the size of the Text component
![image](https://user-images.githubusercontent.com/25371937/198687967-209be878-7324-40ea-99ed-d59f84143e02.png)

**Comment by icflorescu** [comment]
It's a bit unclear to me what you're trying to achieve.
Why would you want to render a `Text` with a `{ width: ... }` style? Doesn't column width satisfy your case?

Anyway, I am unable to reproduce the bug. This works perfectly for me:

```ts
    <DataTable
      columns={[
        { accessor: 'name', width: 200, render: ({ name }) => <Text style={{ width: 70 }}>{name}</Text> },
        { accessor: 'streetAddress' },
        { accessor: 'city' },
        { accessor: 'state' },
      ]}
      records={companies}
    />
```
![image](https://user-images.githubusercontent.com/581999/198735999-47091c43-827c-4f1c-a6ac-29622d7350cf.png)

Can you add a link to a codesandbox reproducing the problem?

**Comment by OSiG43** [comment]
I finally managed to find that `ellipsis:true` is the cause of this problem.

I don't know if it's a bug but when `ellipsis:true` there is no automated line break.
But, now that I think about it, it doesn't make sense to have `ellipsis:true` if I use the render option. So it's probably not a bug, sorry for this issue. I think I can close the issue ?

By the way, I'm not just using the column width because I need to put a button aside the Text.

**Comment by icflorescu** [comment]
Ah, I see. It makes sense. You'd usually do `ellipsis: true` when you **want** your content to be truncated with ellipsis and have no line breaks.
See https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/.
That's why I added the CSS attribute `whiteSpace: 'nowrap'`.
So it's actually not a bug.

In this particular case, indeed you shouldn't used `ellipsis: true`.
