### ISSUE TITLE
Weird lone table cell only visible on dark mode

### ISSUE THREAD

**Issue by italodeandra** [icflorescu/mantine-datatable#11]
![image](https://user-images.githubusercontent.com/19225266/188345180-b1743b03-7d30-4cf3-b187-9e1b1531e88d.png)

**Comment by icflorescu** [comment]
Good catch, thanks!
I'll look into it.

**Comment by icflorescu** [comment]
Already fixed, will publish as soon as I manage to get rid of `lodash`.
