### ISSUE TITLE
Wrong position of context menu in RTL

### ISSUE THREAD

**Issue by ShahriarKh** [icflorescu/mantine-datatable#110]
The context menu doesn't work correctly with RTL.

Here are two screenshots. The red cross is where I right-clicked to open the menu.
![image](https://user-images.githubusercontent.com/31452340/198876680-28578da0-186f-4171-a436-157983052098.png)
![image](https://user-images.githubusercontent.com/31452340/198876698-21091949-98de-45cc-bd3e-d0e845dd7846.png)

Other things are working correctly. The table data is correctly filled from right to left, and even the menu options are correctly in RTL (notice the position of icons and text-alignment). However, the position for specifying where the menu should open is mirrored.

**Comment by ShahriarKh** [comment]
I think the solution is to calculate the `desiredRight` if the app is in RTL mode.
https://github.com/icflorescu/mantine-datatable/blob/ceaa83545c0b0b647eb1e6369332f9a3bae75833/package/DataTableRowMenu.tsx#L45

**Comment by icflorescu** [comment]
Hey @ShahriarKh, thanks for raising the issue!
Please let me know if `v.1.7.12` solves the issue.

**Comment by ShahriarKh** [comment]
@icflorescu Thank you for your fast response!
Yes, the issue is solved. 👍🏽
