### ISSUE TITLE
Selecting single record

### ISSUE THREAD

**Issue by shahns** [icflorescu/mantine-datatable#112]
**Is your feature request related to a problem? Please describe.**
Currently, the way of selecting records allows for multiple record selection. Is there out-of-the-box way to restrict selection to single record only?

**Comment by icflorescu** [comment]
Not at the moment.
Do you think we should implement this as a new feature?
If so, can you please elaborate on how you'd like it to work?
For instance, in case of single-record selection, should we render a Checkbox or a Radio?

**Comment by ShahriarKh** [comment]
How about this?
```jsx
const [selectedRecords, setSelectedRecords] = useState([]);

<DataTable 
    selectedRecords={selectedRecords}
    onSelectedRecordsChange={setSelectedRecords}
    isRecordSelectable={(record) => record == selectedRecords[0] || selectedRecords.length < 1}
/>
```

**Comment by shahns** [comment]
> Not at the moment. Do you think we should implement this as a new feature? If so, can you please elaborate on how you'd like it to work? For instance, in case of single-record selection, should we render a Checkbox or a Radio?

A property `allowMultipleSelect` can be added which makes sure only current selected record is added to `selectedRecords` state.

I would still go ahead with checkbox and removing checkbox from the header field.

**Comment by shahns** [comment]
> ```js
>     isRecordSelectable={(record) => record == selectedRecords[0] || selectedRecords.length < 1}
> ```

I tried this. Still I could select multiple items by clicking header checkbox. 

![image](https://user-images.githubusercontent.com/11992778/199451022-02786546-02c2-4e25-b351-460e4ca92400.png)

Also, this requires me to uncheck the selected record every time before checking the new record.

**Comment by otobot1** [comment]
I think if you are only able to select one row then a radio would be more clear. But I think making that configurable (with radio as default) would be ideal.

**Comment by shahns** [comment]
Hi, does community feel this feature is important and is it planned sometime in near future? If not, I don't mind closing this issue.

**Comment by russocorp** [comment]
Single record selection clicking on line is really cool.
With this, i can get ID from clicked line and use for edit item and other things too.

**Comment by icflorescu** [comment]
@russocorp You can easily get the record data of a clicked row with `onRowClick`: [handling-row-clicks](https://icflorescu.github.io/mantine-datatable/examples/handling-row-clicks)

**Comment by icflorescu** [comment]
In the end, since this is really an edge case, I'd suggest using a custom column with a `render` function showing a [<Radio /> component](https://mantine.dev/core/radio/).

**Comment by russocorp** [comment]
> @russocorp You can easily get the record data of a clicked row with `onRowClick`: [handling-row-clicks](https://icflorescu.github.io/mantine-datatable/examples/handling-row-clicks)

I know that, but after click, line dont have a diferent background or something like that.
https://www.ag-grid.com/react-data-grid/row-selection/ have this, for example.

**Comment by icflorescu** [comment]
@russocorp Since you'll have to manage the selected row in your state anyway, you could easily apply your own particular style to it: https://icflorescu.github.io/mantine-datatable/examples/additional-styling#row-styling
