### ISSUE TITLE
Custom Loader Enhancement

### ISSUE THREAD

**Issue by dukesx** [icflorescu/mantine-datatable#116]
**Is your feature request related to a problem? Please describe.**
Yes and No. I Have a scenario. When i delete data for example, i show table loader, now that is alright but deleting sometimes takes time and that can panic some people into believing that maybe internet got disconnected or there is an error. An article who has comments, tags and much more linked in Postgres, can take such long times naturally. 

**Describe the solution you'd like**
I think you use Mantine's Loader Overlay , it has an option to provider custom loader if needed. How about giving us a customLoader props to fill that "loader" prop of Loader Overlay ? As simple as it gets and the rest is end user's issue.

**Describe alternatives you've considered**
I wouldn't choose anything above Mantine Data table. 

**Additional context**
Simple issue, its just a prop that will be optional in interface or type, if customLoader && loader={customLoader}

**Comment by icflorescu** [comment]
Sounds useful. Will do it soon.

**Comment by icflorescu** [comment]
This was implemented and released in `v1.7.14` 🎉
See **Using a custom loader component** section on the [asynchronous data loading example page](https://icflorescu.github.io/mantine-datatable/examples/asynchronous-data-loading).
