### ISSUE TITLE
Unable to select row text with row selection enabled.

### ISSUE THREAD

**Issue by Daxble** [icflorescu/mantine-datatable#14]
**Describe the bug**
Enabling row selection results in column text being unselectable.

**To Reproduce**
1. Enable row selection on a table
2. Try to select text in the table

**Expected behavior**
Text to be selectable with row selection.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 104.0.5112.102

**Additional context**
It seems like maybe clicking a row would select the whole row, but nothing happens instead. Being able to still select text would be extremely useful.

**Comment by icflorescu** [comment]
> Enabling row selection results in column text being unselectable

This behavior is intentional; I deliberately disabled text selection when row selection in enabled. I found it to be confusing (especially on touch-screen devices), but maybe it wasn't such a good idea since you're seeing this as a bug.

**Comment by icflorescu** [comment]
Let's discuss this: https://github.com/icflorescu/mantine-datatable/discussions/15

**Comment by icflorescu** [comment]
By default text selection is going to be enabled, we'll have a property called `textSelectionDisabled`.

**Comment by icflorescu** [comment]
This should be fixed in a few minutes, as soon as `v1.1.1` hits the npm registry.
