### ISSUE TITLE
is there a way to add an HTML attribute for every record ❓ 

### ISSUE THREAD

**Issue by BadrEddineMoufid** [icflorescu/mantine-datatable#142]
is there a way to add an HTML tag for every record,  for example I want to add data-cy="equipment-item" to every item rendered by the DataTable component so that I can get it in cypress without having to set the render function and return custom component  for every column object

**Comment by icflorescu** [comment]
Not yet, but seems like a good idea. I'll think of a way to make this generic enough to be usable in various testing scenarios.

**Comment by icflorescu** [comment]
I'd name this "adding an HTML **attribute**", though...

**Comment by icflorescu** [comment]
Note: this will also need to be documented.

**Comment by BadrEddineMoufid** [comment]
thank you much appreciated

**Comment by icflorescu** [comment]
This landed in `v1.7.24` 🎉
See docs here: https://icflorescu.github.io/mantine-datatable/examples/custom-row-or-cell-attributes
