### ISSUE TITLE
Filtering on individual columns

### ISSUE THREAD

**Issue by khalibloo** [icflorescu/mantine-datatable#144]
**Is your feature request related to a problem? Please describe.**
There doesn't appear to be a way to add a filter button to the column title. Here is an example https://ant.design/components/table#components-table-demo-head where the columns have sort and filter buttons.

**Describe the solution you'd like**
If a column is marked as filterable, it should be able to provide simple filtering options based on the data type of the column, or allow one to provide a ReactNode that would be rendered in the overlay when the filter button is clicked.

**Describe alternatives you've considered**
I could not find a way to achieve this, but I suspect that by providing a ReactNode as the title, I could sneak in a filter button there. Its placement and functionality would still have to be manually defined though, rather than a convenient built-in solution.

**Comment by icflorescu** [comment]
This would undoubtedly be a useful feature. It has been discussed before and don't have much time to address this till the end of the year, but it sounds like a perfectly valid reason to [make the column header accept a function](https://github.com/icflorescu/mantine-datatable/discussions/126), to begin with. In fact, I think I'll just do that.

**Comment by AlexcastroDev** [comment]
> This would undoubtedly be a useful feature. It has been discussed before and don't have much time to address this till the end of the year, but it sounds like a perfectly valid reason to [make the column header accept a function](https://github.com/icflorescu/mantine-datatable/discussions/126), to begin with. In fact, I think I'll just do that.

Today i use this package in my company: https://github.com/AlexcastroDev/flexysearch
based on Mui Datagrid PRO.

You can check if is good for this project, or if needed, i can update to help mantine-datatable.

Cheers
