### ISSUE TITLE
Missing border-left when using withColumnBorders

### ISSUE THREAD

**Issue by darwinhace** [icflorescu/mantine-datatable#155]
**Describe the bug**
Missing border-left when using column borders, on the last column

**To Reproduce**
1. Go to ['Mantine datatable getting started'](https://icflorescu.github.io/mantine-datatable/getting-started)
2. You can see the last column missing border-left

**Expected behavior**
Border on all column appears when using 'withColumnBorders'

**Screenshots**
![ss](https://user-images.githubusercontent.com/76155308/208545526-bab56fba-eabd-4a45-a495-092d8b8bf0c7.png)

**Comment by icflorescu** [comment]
Thanks a lot for raising. Probably a regression happening due to a newer Mantine core version.
Fixed by increasing CSS specificity.
Released in `v1.7.30` 🎉
