### ISSUE TITLE
FEATURE REQUEST: Add hovers for default column titles

### ISSUE THREAD

**Issue by capaj** [icflorescu/mantine-datatable#157]
**Is your feature request related to a problem? Please describe.**
Not being able to read title of a column "Q..." like this

![image](https://user-images.githubusercontent.com/1305378/208910943-7b9782a0-fefa-4f3b-944e-bbca907f0365.png)

**Describe the solution you'd like**
display who name of column on hover

**Describe alternatives you've considered**
I could implement this myself, but would be better if Datatable had it by default

**Additional context**

**Comment by capaj** [comment]
I was thinking mantine tooltip but title might work too

**Comment by icflorescu** [comment]
I find Mantine's Tooltip a bit too intrusive in this context, so let's go with title.
Should be fixed in a couple of minutes in `v.1.7.31`, as soon as the build pipeline runs.
