### ISSUE TITLE
FEATURE REQUEST: have a way to centrally define rendering for certain types

### ISSUE THREAD

**Issue by capaj** [icflorescu/mantine-datatable#169]
**Is your feature request related to a problem? Please describe.**
I use trpc and often I have Date objects in my data.
When I define a simple accessor to render it in DataTable, I get:

```
react-dom.development.js:14887 Uncaught Error: Objects are not valid as a React child (found: [object Date]). If you meant to render a collection of children, use an array instead.
```

**Describe the solution you'd like**
would be nice to be able to extend datatable, maybe like this:

```tsx

export const ExtendedDataTable = () => {
  return <DataTable defaultColumnRender={(item, accessor) => {
  // my custom rendering function
}} />
}
```

**Describe alternatives you've considered**
alternative is to have this render function imported in each file and manually set it for each column

**Additional context**

**Comment by youssefhabri** [comment]
Mantine Datatable already has a way to achieve this, if I understand you request correctly:

```ts
<DataTable
  columns={[
    {
      accessor: 'name',
      render: (item) => <Text>{item.name}</Text>,
    },
  }]
/>
```

Maybe this is what you're looking for?

**Comment by capaj** [comment]
No that is just a regular render function for one column. I would like to define a single explicit function which is used by default for any column which doesn't define a render function.

**Comment by icflorescu** [comment]
This feature is available in `v.1.7.35`. See the [default column render](https://icflorescu.github.io/mantine-datatable/examples/default-column-render) example for additional information.
