### ISSUE TITLE
Wrapping {records.map} for Animations

### ISSUE THREAD

**Issue by hilmia** [icflorescu/mantine-datatable#178]
I would like to use libraries like [flipMove](https://github.com/joshwcomeau/react-flip-move) and [AutoAnimate](https://github.com/formkit/auto-animate) to enable animations between row changes (add, delete rows). 

Could you add a prop to be able to wrap the records.map in the tbody, as that's required by those libraries to make the animations work.

Thank you for the Datatable, it's great!

**Comment by icflorescu** [comment]
Starting with `v1.8.0`, Mantine DataTable exposes a `bodyRef` property that can be used with AutoAnimate 🎉
See [icflorescu.github.io/mantine-datatable/examples/using-with-auto-animate](https://icflorescu.github.io/mantine-datatable/examples/using-with-auto-animate) for an example.

**Comment by hilmia** [comment]
Hi @icflorescu , thanks for the update.

It works, but I'm getting a type error: 

`Type 'RefObject<HTMLTableSectionElement>' is not assignable to type '(instance: HTMLTableSectionElement | null) => void'.
  Type 'RefObject<HTMLTableSectionElement>' provides no match for the signature '(instance: HTMLTableSectionElement | null): void'.ts(2322)`

I used the doc example:

```
const [bodyRef] = useAutoAnimate<HTMLTableSectionElement>();

return (
    <>
      <EditActivityModal editingItem={editingItem} modalState={[editModal, setEditModal]} />
      <Box sx={{ height: "calc(100vh - 210px)" }}>
        <TableFilters setFilters={setFilters} />
        <DataTable
          bodyRef={bodyRef}
          withBorder
          shadow="xs"
          fetching={isLoading}

.....
```
Is there something that I did wrong?

**Comment by icflorescu** [comment]
That's strange. I'm not getting the error locally.
Can you please try `v1.8.1` and see if the problem persists?

**Comment by hilmia** [comment]
> That's strange. I'm not getting the error locally. Can you please try `v1.8.1` and see if the problem persists?

v1.8.1 fixed it, thank you!
