### ISSUE TITLE
Incorrect arrow for sorting asc/desc

### ISSUE THREAD

**Issue by imoby** [icflorescu/mantine-datatable#191]
**Describe the bug**
The arrow for sorting ascending / descending is reversed currently. It is industry standard that when it is descending that the arrow be faced down but currently desc is showing arrow facing up. The fix is to simply change the following in the `DataTableHeaderCell.tsx` file from `desc` to `asc`

```
  <ArrowDown
      className={cx(classes.sortableColumnHeaderIcon, {
        [classes.sortableColumnHeaderIconRotated]: sortStatus.direction === 'asc',
      })}
      size={14}
  />
```

I would submit a PR but I do not have permissions.

Here are two industry standards:
<img width="794" alt="Screen Shot 2023-02-28 at 1 02 38 AM" src="https://user-images.githubusercontent.com/6380855/221779508-55dfb635-fc96-43ce-93ee-730ce80e3fd3.png">

<img width="1212" alt="Screen Shot 2023-02-28 at 1 02 49 AM" src="https://user-images.githubusercontent.com/6380855/221779501-7ce6a047-3458-4097-ad11-17aa015c90f2.png">

**To Reproduce**
1. Go to sorting example
2. Click on any column header that allows sorting
3. Notice that for desc/asc it is reverse icon

**Expected behavior**
The icon should show facing down for desc and facing up for asc

**Screenshots**
See above

**Desktop (please complete the following information):**
 All Desktop

**Smartphone (please complete the following information):**
All Mobile

**Additional context**

**Comment by mpinedami** [comment]
Taking advantage of this issue there is a possibility that there is a way to reduce the space in the header name and the sort arrows?

Currently I feel that the space between both elements is a very large one.

**Comment by icflorescu** [comment]
Thanks @imoby! Will fix this today.
@mpinedami - opinions are purely subjective, but I think you're right :-) I'll make it something like `0.25em`.
