### ISSUE TITLE
Ghost Records

### ISSUE THREAD

**Issue by wildsonc** [icflorescu/mantine-datatable#193]
**Describe the bug**
I couldn't simulate this error on purpose, but it happens frequently, when I change the records or change to a page with a new table/records but it continues with the previous data.

Maybe it's my mistake, I have no idea.

**To Reproduce**
Change records or change page with another table

**Screenshots**
![CleanShot 2023-03-03 at 14 12 18](https://user-images.githubusercontent.com/72408418/222784792-6a63cb4e-e8bb-4af4-bb64-2e25830b7334.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome

**Comment by icflorescu** [comment]
I don't understand what you're logging to the console.
Please feel free to reopen if you can provide a link to a codesansbox (or an alternative) reproducing the issue.
