### ISSUE TITLE
Compatibility with Mantine 6 (Pagination)

### ISSUE THREAD

**Issue by maltekiessling** [icflorescu/mantine-datatable#194]
**Describe the bug**
With version 6 of the Mantine package they introduced a couple of braking changes.
The list of breaking changes is long and I don't know what is relevant for mantine-datatable.
But I noticed one compatibility bug regarding the pagination feature:

If the page is changed from outside the DataTable component the `paginationTextValue` changes but the Mantine pagination component doesn't.

In the DataTableFooter component the Mantine pagination is called like this:
```tsx
<Pagination
  color={paginationColor}
  className={cx(classes.pagination, { [classes.paginationFetching]: fetching || !recordsLength })}
  page={page}
  onChange={onPageChange}
  size={paginationSize}
  total={Math.ceil(totalRecords! / recordsPerPage!)}
/>
```

According to the [documentation of breaking changes](https://mantine.dev/changelog/6-0-0/#pagination-breaking-changes) the pagination prop `page` was renamed to `value`. This seems to cause the problem.

**To Reproduce**
1. Install mantine-datatable@1.8.6
2. Install Mantine packages @6.0.0
3. Use Pagination feature of mantine-datatable
4. Change page from outside of DataTable component

**Expected behavior**
The pagination bar should show the selected page.

**Screenshots**
After page change from page 3 to page 1 triggered from outside the DataTable component, the `paginationTextValue` on the left side indicates page 1 while the Mantine pagination on the right stays on page 3.
<img width="892" alt="image" src="https://user-images.githubusercontent.com/30420110/223134595-70e4053f-49f9-4b0d-b4ad-10bf864e0743.png">

**Comment by icflorescu** [comment]
Thanks!
I'm aware of the breaking changes.
Compatibility with Mantine 6 is the next thing to be addressed; hope to find the necessary time within the next couple of days.
Due to the breaking changes, I'll most likely bump `mantine-datatable` version to `2.0` and follow Mantine's naming conventions.

**Comment by icflorescu** [comment]
Make sure to use Mantine DataTable `v2.x` or newer with Mantine `v6.x` 🚀
**There are no breaking changes in the new `mantine-datatable` package**, but adjusting the documentation website wasn't as straightforward as I was hoping due to lots of breaking changes.
