### ISSUE TITLE
Custom Render Overlap with Row Selection

### ISSUE THREAD

**Issue by Daxble** [icflorescu/mantine-datatable#20]
**Describe the bug**
When using a custom render function, items will overlap the row selection box when scrolled to the right on the table.

**To Reproduce**
1. Enable row selection on table
2. Add custom render function with an element instead of text
`render: () => (<Avatar>BM</Avatar>)`

**Screenshots**

**Top has z-index: 1 on the row selection box**
![image](https://user-images.githubusercontent.com/85771684/189159105-cfc09205-7367-42be-8211-316be82677ed.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 105.0.5195.102

**Additional context**
Adding z-index: 1 to the row selection box appears to fix the issue.

**Comment by icflorescu** [comment]
Good catch, thanks!

I can reproduce the issue and indeed it looks like adding `z-index: 1` to the  `<td>` containing the selection checkbox is the way to fix it.

Will publish a new version in a few minutes.

**Comment by icflorescu** [comment]
The fix should now be published in `v1.2.2`.
