### ISSUE TITLE
Support column groups

### ISSUE THREAD

**Issue by erikash** [icflorescu/mantine-datatable#207]
**Is your feature request related to a problem? Please describe.**
We have columns which need to be grouped by a common denominator - something like this:
![image](https://user-images.githubusercontent.com/140349/224980058-33a6bb81-cacc-4f87-80f4-682cb650183c.png)

**Describe the solution you'd like**
It would be great to support column groups as per the image above.

**Describe alternatives you've considered**
For now I'm prefixing each column separately for example:
Medical Plan - Name
Medical Plan - Carrier
This doesn't look very well...

**Additional context**

**Comment by icflorescu** [comment]
Implementing this in a way that doesn't break existing functionality (i.e. columns with `hidden` & `visibleMediaQuery` props) would not be exactly trivial.
I'm open to accepting PRs if somebody can come up with a solution.

**Comment by mcmxcdev** [comment]
We would really badly need this feature, since the implementation of mantine `Table` accepts any kind of DOM nodes as children while `mantine-datatable` requires columns and records.

This leads to us having to pick if we want sorting and filtering but no column groups (mantine-datatable) or column groups but no sorting and filtering (mantine native `Table`)

**Comment by icflorescu** [comment]
@mcmxcdev:
See my comment above. I'll try to come up with a solution, but the trick is to make this feature work with columns that are `hidden` or have the `visibleMediaQuery` attribute set. As stated above, I'd like to have this implemented too, so I'm **more** than open to suggestions or PRs, if someone can come up with a solution before me.

Thank you for your patience and for using Mantine DataTable!

**Comment by MatthijsMud** [comment]
Another thing to consider is how this would affect the API. Adding a prop that serves as an alternative to `columns` (i.e. `groups`) would probably be the most straight-forward option.

```tsx
<DataTable
  data={[/* … */]}
  groups={[
    {
      key: "",
      component: <></>,
      columns: [/* … */] 
    },
    {
      key: "",
      component: <></>,
      columns: [/* … */] 
    },
  ]}
/>
```

This still leaves the issue of the `hidden` and `visibleMediaQuery` props. The former shouldn't be too hard to deal with; simply count the number of columns where `hidden` is `false` and use that as the `colSpan` for the header cell. 

In a way, this also applies for the result of `visibleMediaQuery`, the main issue is getting that result. We cannot use [Mantine's `useMediaQuery` hook](https://github.com/mantinedev/mantine/blob/8c12a76c56da51af34213f18dd67c8b72a0ddb44/src/mantine-hooks/src/use-media-query/use-media-query.ts) for this purpose, as we we'd have to invoke it a variable number of times… [which React doesn't like](https://react.dev/learn/state-a-components-memory#how-does-react-know-which-state-to-return).

Modifying the [hook's code](https://github.com/mantinedev/mantine/blob/8c12a76c56da51af34213f18dd67c8b72a0ddb44/src/mantine-hooks/src/use-media-query/use-media-query.ts) such that it works on an array of media queries instead would probably solve this issue. When doing so, it might also be worth performing the query directly in `DataTable.tsx`, and filtering out any columns which end up "hidden"; that way you prevent each cell in the given column from invoking the same media query.

Ignoring that last point, the rendering of header groups could then be implemented something along the lines of:

```tsx
// DataTableHeaderGroup.tsx
export const DataTableHeaderGroup: FC = ({ columns, component }) => {
  const mediaQueries = useMemo(() => columns.map(column.visibleMediaQuery), [columns]);
  const queryResults = useMediaQueries(mediaQueries); // boolean[]
  const numberOfVisibleColumns = useMemo(() => { 
    return columns.filter((column, i) => queryResults[i] && !column.hidden).length
  }, [queryResults, columns]);

  return numberOfVisibleColumns == 0 ? null : <th colSpan={numberOfHiddenColumns}>
    { component }
  </th>
};
```

```tsx
// DataTableHeader.tsx
// …
<thead>
  {groups ? <tr>
    {selectionVisible ?? <th></th>}
    {groups.map(group => <DataTableHeaderGroup {...group} />)}
  </tr> : null}
  <tr>{/* … */}</tr>
</thead>
```

I'll leave it as a suggestion for now.

**Comment by adlid** [comment]
is this work for nested groups?

**Comment by icflorescu** [comment]
@adlid see https://icflorescu.github.io/mantine-datatable/examples/column-grouping

**Comment by DanyloIvashev** [comment]
@icflorescu there no information about nested groups…
