### ISSUE TITLE
Rem warnings in console

### ISSUE THREAD

**Issue by imoby** [icflorescu/mantine-datatable#221]
**Describe the bug**
As of 2.0 version, I'm starting to see warnings in the console that mention things like:
`Unexpected value 1.375rem parsing width attribute.`

and this only happens in places that use mantine datatable. It will log this many times in my console. I've upgraded my mantine version to 6.0 too

**To Reproduce**

1. Create a project with mantine 6.0 and add mantine data table
2. Observe when adding data, in my case about 5+ columns, that there are warnings that show in the console

**Expected behavior**
Warnings should not be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/6380855/226259683-516fa341-c1a2-4ece-b8c7-77722da1b2fb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by icflorescu** [comment]
Judging from your screenshot, I understand this happens on Firefox.

I've noticed similar warnings related to Mantine 6.x and most likely it's something to do with their [migration to rem units](https://mantine.dev/changelog/6-0-0/#migration-to-remem-units).
Unfortunately there's nothing I can do about it in Mantine DataTable, as the warnings are coming from the underlying components I'm using.

Do you see similar warnings when accessing various pages in [mantine.dev](https://mantine.dev/)?

**Comment by icflorescu** [comment]
See here: https://github.com/mantinedev/mantine/issues/3885

**Comment by icflorescu** [comment]
I'm going to close this for now, since it's not strictly related to Mantine DataTable but to Mantine.
