### ISSUE TITLE
Umlaute and special characters are not being rendered when used in a column accessor

### ISSUE THREAD

**Issue by Akashic101** [icflorescu/mantine-datatable#223]
**Describe the bug**
When using Umlaute such as Ä,Ö,Ü,ä,ö,ü or special characters such as ?,_,-,',* are not being displayed when used in a column accessor

**To Reproduce**
Create a Datatable similar to this:

```
<DataTable
	records={records}
	columns={[
		{ accessor: "normal letters rendering" },
		{ accessor: "ÄÖÜäöü not rendering" },
		{ accessor: "?`*'_ not rendering" },
	]}
/>
```

**Expected behavior**
All letters should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/39961794/226889639-87444ab3-e515-498e-b759-8efa3b8e7ab4.png)

**Desktop (please complete the following information):**

- OS: WIndows 10
- Browser Chrome
- Version 111.0.5563.110

**Comment by Akashic101** [comment]
Figured it out myself, if you use the `title` attribute the text gets rendered correctly

```
<DataTable
	records={records}
	columns={[
		{ accessor: "normal letters rendering" },
		{ accessor: "ÄÖÜäöü not rendering", title:  "ÄÖÜäöü rendering" },
		{ accessor: "?`*'_ not rendering", title: "?`*'_ rendering"  },
	]}
/>
```

**Comment by icflorescu** [comment]
That is indeed the correct way of handling this scenario.

As a convenience, if you don't provide a title, the component will try to infer one by "humanizing" the accessor (see [this internal method](https://github.com/icflorescu/mantine-datatable/blob/main/package/utils.ts#L13)), but this can only help if the acessors follow the standard naming patterns (i.e. `firstName` accessor resolves to `First name` title).

Hence the necessity of providing the `title` attribute for special cases or if you're not happy with the automatically inferred one.
