### ISSUE TITLE
Setup Jest

### ISSUE THREAD

**Issue by AlexcastroDev** [icflorescu/mantine-datatable#225]
**Is your feature request related to a problem? Please describe.**

Unit test and coverage to improve this project

**Describe the solution you'd like**
- Start using Jest and other testing tools
- Configure Jest for your project
- Start having minimum coverage

**Describe alternatives you've considered**
....

**Additional context**
....

**Comment by icflorescu** [comment]
Thanks a lot for this, much appreciated!
Feel free to add more tests whenever you have time!
