### ISSUE TITLE
Allow Pointer Events for Empty State

### ISSUE THREAD

**Issue by Yoshify** [icflorescu/mantine-datatable#234]
**Is your feature request related to a problem? Please describe.**
I encountered this issue with a specific purpose in mind - if the table is empty, include a button component in emptyState to allow the user to create records.
Unfortunately buttons in empty state aren't clickable as the parent Center element above the empty state has `pointerEvents: 'none'`
Manually removing this allows the user to interact with Buttons.

**Describe the solution you'd like**
Ideally, a way to interact with buttons in an empty state. Optional or not.

**Additional context**
It appears to be related to the `pointerEvents: 'none'` at line 13 in DataTableEmptyState.tsx
https://github.com/icflorescu/mantine-datatable/blob/1d40bb8d9b9866e31fab7311f7b1f569b6c9c7e8/package/DataTableEmptyState.tsx#L13

Unrelated, but this repo is fantastic and has really helped quickly create great tables with Mantine - thank you!

**Comment by Yoshify** [comment]
Wrapping the empty state in a component with a style with `pointerEvents: all` works - I tried this initially, and didn't think this worked, but turns out I was just working with cached data.

**Comment by Arcade1080** [comment]
@Yoshify this works, but your empty state components are clickable even if the table has content.
