### ISSUE TITLE
Pass event to `onCellClick`

### ISSUE THREAD

**Issue by zbraniecki** [icflorescu/mantine-datatable#250]
**Describe the solution you'd like**

At the moment, there's no way to tailor down the click to double-click because the handler doesn't receive the event as an argument. Passing it would allow the handler to decide whether it wants to act on click or double click.

**Comment by icflorescu** [comment]
Implemented in `v2.4.1`. The original event is now passed to `onCellClick` and `onRowClick` handlers.
But I don't see how this would enable you to *tailor down the click to double-click*.

Let me know if you think having two props called `onCellDoubleClick` and `onRowDoubleClick` would be useful.
