### ISSUE TITLE
Summary row / Footer

### ISSUE THREAD

**Issue by petrvecera** [icflorescu/mantine-datatable#252]
Is it possible to have a summary row right now ? 

If not, it would be great to have option for this. 

Examples:
https://www.mantine-react-table.com/docs/guides/data-columns#custom-footer-render
https://ant.design/components/table#components-table-demo-summary

I am able to calculate simple summary but than I realized that I need to style it in each column differently. 

_PS: Thanks for a great library 👍_

**Comment by icflorescu** [comment]
Thanks for the kind words and the sponsorship!
No, I'm afraid not at the moment.

Do you think it would it be good enough if each column have these optional properties?
- `footer: ReactNode`
- `footerClassName: string`
- `footerStyle: CSSProperties`
- `footerSx: Sx`

**Comment by icflorescu** [comment]
This will be available in a few minutes, as soon as `v2.4.9` hits the npm registry.
