### ISSUE TITLE
Allow for not displaying thead

### ISSUE THREAD

**Issue by zbraniecki** [icflorescu/mantine-datatable#253]
**Describe the solution you'd like**

There are cases, such as nested table, where it would be useful to skip the `thead` display.

I'm currently workarounding it by setting `titleStyle: { display: 'none' }` on each column.

**Comment by icflorescu** [comment]
This would be fairly easy to implement.

How would you call the prop?
- `withoutHeader`
- `noHeader`
- something else

**Comment by zbraniecki** [comment]
I'm not super familiar with React API design, but my guess would be that `header: boolean` would allow you to later grow that to `boolean | Options`.

**Comment by icflorescu** [comment]
Went with `noHeader` in the end.

See examples using this feature:
- [Nested tables](https://icflorescu.github.io/mantine-datatable/examples/nested-tables)
- [Nested tables with async loading](https://icflorescu.github.io/mantine-datatable/examples/nested-tables-with-async-data-loading)
- [Nested tables with async loading & sorting](https://icflorescu.github.io/mantine-datatable/examples/nested-tables-with-async-data-loading-and-sorting)

**Comment by icflorescu** [comment]
Implemented in `v2.4.6`.

Speaking of React API design, AFAIK it's desirable to have `boolean` props defaulting to `false`.
That's partially why I went with `noHeader`; I'm not a fan of having to specify a `prop={false}` for a React component.
