### ISSUE TITLE
How to force dark/light mode for DataTable

### ISSUE THREAD

**Issue by WenLonG12345** [icflorescu/mantine-datatable#280]
Hi, thanks for this awesome library. 
However, I found that there is no `theme` options for us to force the table to stick to light/dark mode. 
Is there such a feature in Mantine UI? If yes please let me know on this. 
Greatly appreciate any helps!

**Comment by icflorescu** [comment]
Mantine DataTable follows [Mantine UI theming](https://mantine.dev/theming/mantine-provider/).
It wouldn't make much sense yo have your application use a theme and the `DataTable` use a different one, would it?
If, for some reason, that's what you want, you could simply [nest it inside a `ThemeProvider`](https://mantine.dev/theming/mantine-provider/#nested-mantineproviders).

**Comment by icflorescu** [comment]
...and thank you for the kind words :-)

**Comment by WenLonG12345** [comment]
Sorry for late reply and I have this edge cases where one of my table shouldnt follow the root theme. 
By the way thanks for the nesting method, it works for me! 
I would like to contribute in this project, let me see if I can help in any place. :)
