### ISSUE TITLE
ChangeLog updating

### ISSUE THREAD

**Issue by gfazioli** [icflorescu/mantine-datatable#288]
Hey, I just wanted to start off by saying a huge thank you for this amazing component - it's seriously fantastic and very well-written! 👏

I was wondering if you could do me a favour and keep the CHANGELOG updated. Not in a super strict way, but currently I can see that `v2.4.16` has been released, whereas the latest version mentioned in the changelog is `v2.4.9`. This sometimes makes it unclear whether it's safe to update or not. 

Thank you in advance!

**Comment by icflorescu** [comment]
Hey John,

Thanks for the kind words!

The CHANGELOG is kept up to date, in the sense that any bugfixes and/or new features are documented.
Versions that are not mentioned in the CHANGELOG are just dependency updates or very minor internal refactorings (such as fixing typos), so it should be safe to update to something that wasn't mentioned in the changelog.

Let me know if you think this policy should be more visible or if you have a different idea; I'm open to suggestions.

Thanks in advance for your feedback!

**Comment by gfazioli** [comment]
Hey there! 

Thanks a lot for taking the time to explain that. Sorry if I missed it earlier. I totally agree with you - it's a great policy that saves us from having to notify about empty changelogs. Thanks again for your help, it's really appreciated!
