### ISSUE TITLE
'record' is of type 'unknown'

### ISSUE THREAD

**Issue by Nefkens** [icflorescu/mantine-datatable#292]
**Describe the bug**
My code does not compile because of the following error:

Failed to compile.

> #15 5.452
> #15 5.452 ./src/pages/tenant/index.tsx:141:56
> #15 5.452 Type error: 'record' is of type 'unknown'.
> #15 5.452
> #15 5.452   139 |        fetching={isLoading}
> #15 5.452   140 |        sortStatus={sortStatus}
> #15 5.452 > 141 |        onRowClick={(record) => {router.push(`/tenant/${record.uuid}`)}}

This error also trigger on all renders.

>  <DataTable
>        minHeight={450}
>        totalRecords={dataTenant?.pagination?.count}
>        recordsPerPage={pageSize}
>        page={page}
>        withBorder
>        fetching={isLoading}
>        sortStatus={sortStatus}
>        onRowClick={(record) => {router.push(``/tenant/${record.uuid}``)}}
>        onPageChange={(p) => setPage(p)}
>       columns={[{ accessor: 'name', title: 'Name', sortable: true }, 
>       { accessor: 'created_at', title: 'Created', sortable: true, width: 200 , render: (created_at) => Moment({created_at}).format('yyyy-MM-DD')},
>       { accessor: 'modified_at', title: 'Modified', sortable: true, width: 200 }]}
>       records={dataTenant?.results}
>       onSortStatusChange={setSortStatus}
>       recordsPerPageOptions={PAGE_SIZES}
>       onRecordsPerPageChange={setPageSize}
>       idAccessor="uuid"
>     />

Does it have something to do that my id is not a number but a uuid?

**Comment by icflorescu** [comment]
No, it shouldn't.
But I believe your `dataTenant?.results` may not be properly typed:
```ts
records={dataTenant?.results}
```

**Comment by desertspider** [comment]
> No, it shouldn't. But I believe your `dataTenant?.results` may not be properly typed:
> 
> ```ts
> records={dataTenant?.results}
> ```

Thank you for your fast reply.

I am new to Next.js , so maby its my mistake. My code for populating dataTenant:

```
const { dataTenant, isLoading, isError } = getTenants()
function getTenants() {
  const params = new URLSearchParams();
  params.append("page_size", pageSize.toString());
  params.append("page", page.toString());
  params.append("ordering", sortStatus.columnAccessor.toString() + " " + sortStatus.direction.toString());
  //const params = 'page_size=2'
  const { data, error,isLoading } = useSWR('/api/ext/v1/admin/tenant?'+params.toString(), fetcher, {keepPreviousData: true});
  return {
    dataTenant: data,
    isLoading: isLoading,
    isError: isError
  }
}
```

Json from API:
`{
    "pagination": {
        "count": 56,
        "current": 1,
        "end_index": 2,
        "next": 0,
        "previous": 0,
        "start_index": 1,
        "total_pages": 28
    },
    "results": [
        {
            "created_at": "2023-05-14T19:32:14.663506Z",
            "modified_at": "2023-05-14T19:32:14.663506Z",
            "name": "46",
            "uuid": "6d6c6bbb-7cf1-48ee-aaa4-d99ca2782010"
        },
        {
            "created_at": "2023-05-14T19:33:10.889489Z",
            "modified_at": "2023-05-14T19:33:10.889489Z",
            "name": "47",
            "uuid": "0cf4cf13-a082-4a1f-b089-54f39ae66869"
        }
    ]
}`

The question mark is there because if SWR loads the data, dataTenant is null.

**Comment by Nefkens** [comment]
> No, it shouldn't. But I believe your `dataTenant?.results` may not be properly typed:
> 
> ```ts
> records={dataTenant?.results}
> ```

Thank you for your fast reply.

I am new to Next.js , so maby its my mistake. My code for populating dataTenant:

```
const { dataTenant, isLoading, isError } = getTenants()
function getTenants() {
  const params = new URLSearchParams();
  params.append("page_size", pageSize.toString());
  params.append("page", page.toString());
  params.append("ordering", sortStatus.columnAccessor.toString() + " " + sortStatus.direction.toString());
  const { data, error,isLoading } = useSWR('/api/ext/v1/admin/tenant?'+params.toString(), fetcher, {keepPreviousData: true});
  return {
    dataTenant: data,
    isLoading: isLoading,
    isError: isError
  }
}
```

Json from API:
```
{
    "pagination": {
        "count": 56,
        "current": 1,
        "end_index": 2,
        "next": 0,
        "previous": 0,
        "start_index": 1,
        "total_pages": 28
    },
    "results": [
        {
            "created_at": "2023-05-14T19:32:14.663506Z",
            "modified_at": "2023-05-14T19:32:14.663506Z",
            "name": "46",
            "uuid": "6d6c6bbb-7cf1-48ee-aaa4-d99ca2782010"
        },
        {
            "created_at": "2023-05-14T19:33:10.889489Z",
            "modified_at": "2023-05-14T19:33:10.889489Z",
            "name": "47",
            "uuid": "0cf4cf13-a082-4a1f-b089-54f39ae66869"
        }
    ]
}
```

The question mark is there because if SWR loads the data, dataTenant is null.

**Comment by icflorescu** [comment]
I see.
The `useSWR` hook doesn't know how to type your `data`, but since it's a generic, you can easily type it.
See [here](https://swr.vercel.app/docs/typescript#generics).

I'm going to close this, since it's not related to Mantine DataTable.

**Comment by Nefkens** [comment]
You are a hero! Thank you for the support. Got it working.

**Comment by icflorescu** [comment]
Hey @Nefkens, thanks for the kind words, but I am no hero, I assure you! ;-)
I'm glad you got it working.
