### ISSUE TITLE
Allow Custom, or Alternative onSortStatusChange

### ISSUE THREAD

**Issue by HarleySalas** [icflorescu/mantine-datatable#295]
**Is your feature request related to a problem? Please describe.**
Sort status is ColumnA, with direction: 'asc'. You click ColumnB, your sort status is now  ColumnB, with direction **'desc'**.

**Describe the solution you'd like**
The ability to either provide a custom onSortStatusChange function, or an additional prop to DataTable, something like "switchDirectionOnAccessorChange" = false being the answer I would like.

**Additional context**
I'm aware that a lot of tables switch the column direction on columnAccessor change, but I personally find it irritating. I feel that the first click should simply be to change to that columnAccessor. An additional click should be required if you want to change the direction of it.

If you're open to the idea, but don't have the time, just explain the implementation you prefer and I'd be happy to submit a PR.

**Comment by icflorescu** [comment]
What you're saying makes a lot of sense.
I think you're right and we could simply change the default behavior.
First click should change  the sorting column and **keep the current direction**.
I can do it in a few minutes.

**Comment by icflorescu** [comment]
This should be fixed in a few minutes, as soon as `v2.5.0` hits the npm registry.

**Comment by icflorescu** [comment]
Done. Use `v2.5.0` or newer.
Thanks for bringing this to my attention!
