### ISSUE TITLE
Types of parameters '__0' and 'record' are incompatible.

### ISSUE THREAD

**Issue by hilmia** [icflorescu/mantine-datatable#313]
After upgrading from v2.4.16 to 2.5.5 I'm getting type errors in column renders:
` Types of parameters '__0' and 'record' are incompatible.`

For example here:
```
columns={[
                    {
                        accessor: "Title", title: "", width: 200, render: ({ firstName, lastName, profilePic }: {
                            firstName: string, lastName: string, profilePic: string,
                        }) =>
                            <Group><UserAvatar src={profilePic} />{firstName} {lastName}</Group>
                    },
                    { accessor: 'email', width: 140 },
                    { accessor: 'phone', width: 140 },
                    { accessor: 'commissionTitle', width: 240, title: "Commission Plan" },
                    {
                        accessor: "coins", width: 140, render: ({ coins }: {
                            coins: number
                        }) =>
                            <CoinXpRender number={coins} icon="coins" />
                    },
                    {
                        accessor: "xp", width: 140, render: ({ xp }: {
                            xp: number
                        }) =>
                            <CoinXpRender number={xp} icon="xp" />
                    },
                ]}
```

It takes the possible types from the first "render" attribute, so to use {coins} without a type error, I need to add the coins type in the first render types, where I don't use it at all. This wasn't an issue before upgrading

<img width="1222" alt="Screenshot 2023-06-04 at 22 09 31" src="https://github.com/icflorescu/mantine-datatable/assets/69205098/81c558bd-1971-4def-8abd-4010792a1f04">

Please advise if this is a bug or if I should use the render attribute differently now.

Thanks!

**Comment by icflorescu** [comment]
That's strange. There's no change between `2.4.16` and `2.5.5` that should affect this.
Are you sure your `records` are properly typed and include the `coins` attribute?

Try to delete your `node_modules` and `package-lock.json`/`yarn.lock`/`pnpm-lock.json` and reinstall your `npm` modules. I remember seeing weird TS bugs that went away when doing so.

**Comment by hilmia** [comment]
Hi @icflorescu , thank you for your tip. Unfortunately that didn't work. 
 I just added the whole type to the first renders to solve the problem.

**Comment by icflorescu** [comment]
Just wanted to emphasize that in order to have inference working properly, you should make sure to properly **type your `records`**. Typing the `render` function does eliminate the error, but it's kind of a hack and can lead, in time, to a less maintainable code-base.
