### ISSUE TITLE
First Column of Table Missing bottom border

### ISSUE THREAD

**Issue by luffespresso** [icflorescu/mantine-datatable#32]
**Describe the bug**
If you look at the [pagination example](https://icflorescu.github.io/mantine-datatable/examples/pagination), you'll notice that the first column is missing a bottom border:
<img width="973" alt="image" src="https://user-images.githubusercontent.com/93346174/189963231-a094274d-2a6a-453e-bd28-f43aeb1e5f7e.png">

I'm able to reproduce this locally as well with a new table.

Was this intended? I originally assumed it was due to default sorting, but the first column does not look to be sorted in the pagination example.

**Comment by icflorescu** [comment]
Thanks a lot for bringing this up.

Absolutely not intended. And annoying as hell, as I can only reproduce it on iOS (don't have a Mac at the moment). I'm guessing you're using a Mac, right?

I'll have a better look at it tomorrow and see what I can do about it.

**Comment by luffespresso** [comment]
I am on a mac, thanks for the quick reply btw!

**Comment by icflorescu** [comment]
What browser are you using?

I can only reproduce it (on MacOS) on Safari, but not on Chrome or Brave. On iOS I see it happening on Chrome as well...

**Comment by luffespresso** [comment]
> What browser are you using?
> 
> I can only reproduce it (on MacOS) on Safari, but not on Chrome or Brave. On iOS I see it happening on Chrome as well...

I'm using firefox 104 on OSX Monterey
