### ISSUE TITLE
Resizable Columns

### ISSUE THREAD

**Issue by Nishchit14** [icflorescu/mantine-datatable#341]
**Is your feature request related to a problem? Please describe.**
The table columns are not resizable, In my current usecase It is required. It should be a nice feature.

**Describe the solution you'd like**
The table columns should have resize option. with resize options user would be able to set either a specific column, multiple or all columns resizable.

**Comment by ryo-kihara** [comment]
I think so too... 🙏

**Comment by ark-davegoodchild** [comment]
Given that you can set the column width "in code", then you could simply implement this yourself.

**Comment by Nishchit14** [comment]
@ark-davegoodchild didn't get you. Is there any ref or examples?

**Comment by Vikramjeet25** [comment]
@ark-davegoodchild can you give example ?

**Comment by ark-davegoodchild** [comment]
The `width` of a column is configurable, so use state for each of the widths of each of the columns. In the header add a resize icon that when clicked shows an input (or whatever UI you want), that represents the width state for that column, changing it will cause a re-render with the new widths.

**Comment by ark-davegoodchild** [comment]
You could even implement a draggable component in the header that adjusts the width state of that column, that's a bit more work, but easily doable; you just need to get the mouse move event handlers adjusting the width state when moving in the `x` axis.

**Comment by hilmia** [comment]
The second option sounds great, would be nice if there was a column header "render" property like the column cell render property

**Comment by ark-davegoodchild** [comment]
Now that I look a little deeper. The `title` supporting `React.Node | string` would be a nice addition. This would allow people to add icons or whatever they so please to the title element.

**Comment by icflorescu** [comment]
@ark-davegoodchild the `title` **already** accepts a `ReactNode`.

**Comment by ark-davegoodchild** [comment]
OK cool. I didn't/don't see anything to that effect on the docs. Well, there you go @hilmia it's ready and capable for you to add resizing.

**Comment by icflorescu** [comment]
Going to close this, since I'm not planning to implement it as an internal feature. At least not yet.
