### ISSUE TITLE
Option to use ScrollArea.Autosize for dynamic height.

### ISSUE THREAD

**Issue by OrionReed** [icflorescu/mantine-datatable#348]
**Is your feature request related to a problem? Please describe.**
I often work with data where record counts fluctuate from very low to very high. When using datatable to view this data I naturally want a scrollable view when record counts are high but I don't want it to take unnecessary space when there are 0-5 records.

**Describe the solution you'd like**
Mantine has already solved this with `<ScrollArea.Autosize/>` which has a `maxHeight` property that enables scrolling after reaching maxHeight. Because you already have `height` and `minHeight` I think a natural solution is to have a `maxHeight` property which (if it is less than height or if height is not set) will use Mantine.Autosize.

**Describe alternatives you've considered**
Hacking around this by programmatically controlling height, this is clunky and feels very unecessary

**Comment by icflorescu** [comment]
Thanks for raising the issue!
I tried your proposed solution, but for some reason `<ScrollArea.Autosize/>` doesn't play nice with **horizontal** scrolling.
Maybe I'm missing something, so I'd be grateful if you could come up with a PR...

**Comment by OrionReed** [comment]
I'll see what I can come up with, which branch should I point the PR towards? Would you be able to share what you tried on your first pass> It would help me orient myself in the codebase.

**Comment by icflorescu** [comment]
Sure. I've published this branch: [scrollarea-autosize](https://github.com/icflorescu/mantine-datatable/tree/feature/scrollarea-autosize).

You'll be interested in:
- [package/DataTableScrollArea.tsx](https://github.com/icflorescu/mantine-datatable/blob/feature/scrollarea-autosize/package/DataTableScrollArea.tsx)
- [this example component](https://github.com/icflorescu/mantine-datatable/blob/9ceebbe9c41ba712e7b506cca6889d74d4c19e0c/docs/examples/ScrollableVsAutoHeightExamples.tsx#L57) that is being displayed in the last section of [this docs page](https://github.com/icflorescu/mantine-datatable/blob/9ceebbe9c41ba712e7b506cca6889d74d4c19e0c/docs/pages/examples/scrollable-vs-auto-height.tsx#L88)

Run it locally with `yarn dev`, go to http://localhost:3000/examples/scrollable-vs-auto-height, last page section (Using ScrollArea.Autosize) and pay attention to horizontal scrolling...

**Comment by sumann7916** [comment]
> I am having similar issue. @OrionReed How did you achieve AutoSize?

nvm. did this for now.
`height={records.length < 10 ? "auto" : 400}`
