### ISSUE TITLE
Extra white space under the table

### ISSUE THREAD

**Issue by kingRayhan** [icflorescu/mantine-datatable#357]
**Describe the bug**
I am getting extra white space under the table content, by default it's not visible but when I put `withBorder` or `shadow` prop then this empty space appears.

**Expected behavior**
Table height should be fit to it's content rows.

**Screenshots**
<img width="1092" alt="image" src="https://github.com/icflorescu/mantine-datatable/assets/7611746/884fe504-c790-4d30-8ff0-bcb465fdca35">

**Comment by icflorescu** [comment]
Can you please provide a working reproduction (something like codesandbox) to help me identify what's the problem in your specific usage scenario?

The [documentation website](https://icflorescu.github.io/mantine-datatable) includes a lot of `DataTable` instances in the example pages and - as you can see - no extra-space is added anywhere...

**Comment by icflorescu** [comment]
Any feedback on this, @kingRayhan?

**Comment by kingRayhan** [comment]
Thanks for your response. I will come back with a minimal re-production

**Comment by icflorescu** [comment]
Closing as stale.
Please feel free to reopen if you can come up with a minimal reproduction.

Thanks.
