### ISSUE TITLE
Filtering popover will trigger sorting button

### ISSUE THREAD

**Issue by mintong89** [icflorescu/mantine-datatable#368]
**Describe the bug**
Title, if you make a column sortable and filterable, clicking the filtering popover will trigger sorting button.

**Comment by abdullahahmeda** [comment]
I can confirm this bug on v2.6.3
![chrome-capture-2023-6-11](https://github.com/icflorescu/mantine-datatable/assets/23556281/99b07005-260f-429a-a163-64578c3d1b10)

**Comment by icflorescu** [comment]
Well spotted, thanks!
Will publish the fix in a few minutes.

**Comment by icflorescu** [comment]
@mintong89 & @abdullahahmeda The fix is in `2.8.3`.
Thanks again for spotting & fixing this.
