### ISSUE TITLE
Using a DataTable inside of rowExpansion with selectedRecords and noHeader enabled makes checkbox column not adhere to width

### ISSUE THREAD

**Issue by tylertyssedal** [icflorescu/mantine-datatable#387]
**Describe the bug**
Found a bug with using both the `selectedRecords` in a nested `rowExpansion` set with `noHeader`. Appears the lack of header causes the checkbox to not adhere to the header width. This makes sense from the dom's perspective, but perhaps there's a way to enforce it? 

**To Reproduce**

```
      <DataTable
        withBorder
        borderRadius="sm"
        withColumnBorders
        striped
        highlightOnHover
        records={records}
        idAccessor="id"
        sortStatus={sortStatus}
        onSortStatusChange={setSortStatus}
        columns={columns}
        rowExpansion={{
          trigger: "never",
          allowMultiple: true,
          expanded: {
            recordIds: expandedRecordIds,
            onRecordIdsChange: setExpandedRecordIds,
          },
          content: ({record}) => {
            if (!record.children || record.children.length === 0) return null;
            return (
              <DataTable
                noHeader
                idAccessor="id"
                columns={columns}
                records={record.children}
                selectedRecords={selectedRecords }
                onSelectedRecordsChange={setSelectedRecords}
              />
            );
          },
        }}
        totalRecords={data.length}
        recordsPerPage={pageSize}
        page={page}
        onPageChange={(p) => setPage(p)}
        recordsPerPageOptions={pageSizes}
        onRecordsPerPageChange={setPageSize}
        selectedRecords={selectedRecords}
        onSelectedRecordsChange={setSelectedRecords}        
      />
```

**Expected behavior**
Ideally the checkbox columns would be the same width as the parent's. 

**Screenshots**

With `noHeader`: 

<img width="875" alt="image" src="https://github.com/icflorescu/mantine-datatable/assets/9051378/de1dcb92-4bae-471b-9d16-5820e5b534cf">

Without `noHeader`: 

<img width="872" alt="image" src="https://github.com/icflorescu/mantine-datatable/assets/9051378/d94cec1e-1414-4e3b-a542-e8774b11743e">

**Comment by tylertyssedal** [comment]
I have a local fix for this working, but I imagine there'd be utility to having it work like this natively. 

```
.multiple-select {
  td:first-of-type {
    width: 40px;
  }
}

<DataTable
  noHeader
  idAccessor="id"
  columns={columns}
  records={record.children}
  selectedRecords={selectedRecords}
  onSelectedRecordsChange={setSelectedRecords}    
  rowClassName="multiple-select"
/>
```

**Comment by icflorescu** [comment]
Thanks a lot for spotting this!
This should be fixed as soon as the next version hits the `npm` registry; I'll let you know.

**Comment by icflorescu** [comment]
@tylertyssedal - I don't have an example showcasing this, so, can you please check if `v2.9.3` fixes this?
If not, please feel free to reopen the issue.
Thanks a lot!
