### ISSUE TITLE
Select records from all pages

### ISSUE THREAD

**Issue by igomest** [icflorescu/mantine-datatable#410]
I'm testing the library using the official documentation. But I haven't found ways to implement record selection on all pages.

I only found the possibility to select all records per page and not for all pages. Is it possible to implement this functionality using the library?

**Comment by icflorescu** [comment]
Not yet.

At the moment, record selection is implemented with two properties: `selectedRecords` and `onSelectedRecordsChange` and works out-of-the-box for selecting all records per page.

Selecting ALL available records shouldn't be difficult to implement using an "external" button (it's what I did in my projects so far), but it very much depends on your data loading / pagination mechanism.

Having a mechanism that works out-of-the-box to select ALL records would be nice indeed, and I'm open to suggestions and/or pull requests that don't break the existing functionality.

Maybe this could be implemented with some sort of a dropdown menu that gets shown when clicking on the selection header cell; the dropdown menu could present two options - one to select all visible records (current behaviour) and another one to select all AVAILABLE records...

What do you think?

**Comment by icflorescu** [comment]
Here's an example with a possible implementation that I built as part of the new V7 documentation website:

https://icflorescu.github.io/mantine-datatable/examples/records-selection/#selecting-all-records-on-all-pages
