### ISSUE TITLE
mantine-datatable documentation website is crashing on firefox

### ISSUE THREAD

**Issue by argnivb** [icflorescu/mantine-datatable#415]
**Describe the bug**
mantine-datatable documentation website is crashing on firefox developer edition v99.0b8

**To Reproduce**

1. Go to https://icflorescu.github.io/mantine-datatable

**Expected behavior**

**Screenshots**
![m-datatable-site](https://github.com/icflorescu/mantine-datatable/assets/40072715/7d4205bb-9738-4607-8376-023455207075)

**Comment by icflorescu** [comment]
I'm not sure about `v99.0b8`, but it works fine on Firefox 117, on both Windows and Linux (and all common browsers current versions):

![image](https://github.com/icflorescu/mantine-datatable/assets/581999/a73292ea-f04c-4313-a9ea-eeb6281e9002)

Developer editions can have issues and quirks, and TBH I cannot dedicate resources to fix temporary browser issues.

Thanks!
