### ISSUE TITLE
record type appears as unknown

### ISSUE THREAD

**Issue by arifsygl** [icflorescu/mantine-datatable#468]
Thanks for the library.

**Describe the bug**
Hello, in the OnRowClick property, the record type appears as unknown, as seen in the picture. What would be the reason? Thanks

**Expected behavior**
I expect the record to get the type of value in the records array I give.

**Screenshots**
<img width="452" alt="Screenshot 2023-11-09 at 10 24 52" src="https://github.com/icflorescu/mantine-datatable/assets/104317611/3251d2a4-47fb-430e-87de-1afd6c070d51">

<img width="667" alt="Screenshot 2023-11-09 at 10 15 25" src="https://github.com/icflorescu/mantine-datatable/assets/104317611/e274cf28-2e7d-4492-88a6-c58225c4a071">

Thanks for helps

**Comment by icflorescu** [comment]
Thanks for the kind words!

The DataTable **does** infer types from the records array, so the `record` property in the `onRowClick` handler should be properly typed.

I encountered no such issue when building the examples for the documentation website, which is a Next.js + TypeScript application.

Can you please come up with a reproduction (on codesandbox or something similar, or even a small repo on GitHub)?

**Comment by Fiaxhs** [comment]
Just to chime in on the discussion, I had a similar issue when migrating from v6 to v7, and I think you have the same @arifsygl , I had to type the function passed as `onSortStatusChange` to datatable.

Basically:

before
```tsx
const changeSortStatus = (sort: DataTableSortStatus) => { 
    // something something 
}

<DataTable
  onSortStatusChange={changeSortStatus}
  records={records}
  // [...]
/>
```

after
```tsx
                                                  // 👇 this would allow datatable to infer the records properly
const changeSortStatus = (sort: DataTableSortStatus<MyRecordType>) => { 
  // something something 
}

<DataTable
onSortStatusChange={changeSortStatus}
records={records}
  // [...]
/>
```

**Comment by arifsygl** [comment]
Thansk for answers,

I upgraded TypeScript and added the record type to the sortStatus field as you said and it worked. But it might be better if the record gets its type when I don't add the type.

**Comment by twiddler** [comment]
I am facing the same issue. Adding the record type to `DataTableSortStatus<…>` works.

However, this makes for quite verbose code, and I hardly believe this is the intended behaviour. The types should come from the records we pass as `<Datatable records={…} />`, shouldn't they?

**Comment by twiddler** [comment]
Can this be resolved with the new `NoInfer` utility type introduced in [TypeScript 5.4](https://devblogs.microsoft.com/typescript/announcing-typescript-5-4-beta/#the-noinfer-utility-type)?
