### ISSUE TITLE
New Table sticky header feature from mantine/core@7.2.0 breaks sticky headers on 7.1.6 (just FYI)

### ISSUE THREAD

**Issue by isnifer** [icflorescu/mantine-datatable#470]
**Describe the bug**
New Table sticky header feature from `@mantine/core@7.2.0` breaks sticky headers on `mantine-datatable@7.1.6`.
Yes, I know I should be aligned between mantine/core and mantine-datatable, but I love to be on the cutting edge.

This new styles added to `@mantine/core@7.2.0`:
[src/mantine-core/src/components/Table/Table.module.css#R89-R98](https://github.com/mantinedev/mantine/commit/ac108908365f5ea9e7dee4c83f791b6257556349#diff-5cc2999e94fb4319b4eff21b1e5f10d605d1afc04ecd0d0b77bee89792683454R89-R98)

**To Reproduce**

1. Just install 7.2.0 on your next dev round
2. Open example with scrolling, e.g. https://icflorescu.github.io/mantine-datatable/examples/infinite-scrolling/
3. Watch on header and a shadow after scrolling
4. See an error

**Expected behavior**
Sticky headers works side by side with mantine sticky header feature since mantine-datatable@7.2.0

**Screenshots**
Styles applied to `thead` on 7.1.6 (when mantine/core aligned with mantine-datatable)
<img width="325" alt="image" src="https://github.com/icflorescu/mantine-datatable/assets/1788245/3ac46691-c616-4b0d-8fcc-19476f28996a">

mantine/core@7.2.0 adds extra style to `thead` and breaks `mantine-datatable` rules:
<img width="325" alt="image" src="https://github.com/icflorescu/mantine-datatable/assets/1788245/b6126997-efc4-46f1-808d-c2b7a402e954">

Part of the table with a shadow line, but without the header:
<img width="388" alt="image" src="https://github.com/icflorescu/mantine-datatable/assets/1788245/18bd188a-b5fb-4a98-9a34-502c7553f53b">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 119.0.6045.123

**Additional context**
Just FYI issue. Thank you for your library.

**Current workaround**
Set `stickyHeader` property on root component which activates stickyHeaders on `@mantine/core` Table.Thead component and align styles with `mantine-datatable`

**Comment by isnifer** [comment]
Fixed by importing css files in my own `index.css` file by the same order :D

**Comment by icflorescu** [comment]
Yes, I have noticed that forgetting about the CSS order tends to create some confusion. Do you have any suggestion on if/how the documentation could be improved? 

Related to the sticky header behavior, in the last version I've made sure to omit the new `stickyHeader` and `stickyHeaderOffset` props from the underlying Mantine `Table` component, to avoid confusion, since Mantine DataTable header is sticky "as needed" (when vertical scrolling is enabled).

Thanks for closing!

**Comment by lukasbash** [comment]
@isnifer Could you elaborate how you exactly fixed this behaviour? I don't really get how you would rearrange css imports to make this work.

Any chance to get an example code?

**Comment by isnifer** [comment]
@lukasbash yes, sure. My initial problem was — imports inside my entry point (main.tsx in Vite by default). Even all imports were set correctly and `@layer-s` set in root `css-file` I had an issue. I think it relates to how the bundler works, maybe some sort of order is broken, etc.
So, I decided just to move all css imports to root `css-file`.

Now, my top lines of `index.css` look like these:
```css
@layer mantine, mantine-datatable, mantine-contextmenu;

@import '../../node_modules/@mantine/core/esm/index.layer.css';
@import '../../node_modules/@mantine/dates/esm/index.layer.css';
@import '../../node_modules/@mantine/carousel/esm/index.layer.css';
@import '../../node_modules/@mantine/dropzone/esm/index.layer.css';
@import '../../node_modules/@mantine/notifications/esm/index.layer.css';
@import '../../node_modules/mantine-contextmenu/dist/styles.layer.css';
@import '../../node_modules/mantine-datatable/dist/styles.layer.css';
```

Just to be clear, I have a monorepo and no `node_modules` inside every single project.
```
projectRoot
  \ frontend-project-1
    \ src
      \ index.css
    \ package.json
  \ frontend-project-2
  \ frontend-project-3
  \ backend-project
  \ other-project
  \ node_modules (shared between all frontend-projects) 
```

That's why I'm importing like this. If you have standalone project, you can import css from `node_modules` like this:
```css
@layer mantine, mantine-datatable, mantine-contextmenu;

@import '~@mantine/core/esm/index.layer.css';
@import '~@mantine/dates/esm/index.layer.css';
@import '~@mantine/carousel/esm/index.layer.css';
@import '~@mantine/dropzone/esm/index.layer.css';
@import '~@mantine/notifications/esm/index.layer.css';
@import '~mantine-contextmenu/dist/styles.layer.css';
@import '~mantine-datatable/dist/styles.layer.css';
```

So, `~` means `node_modules` in the project root (frontend-project-1 in my case which is empty).
