### ISSUE TITLE
highlightOnHover not working with mantine 7.2.1

### ISSUE THREAD

**Issue by TheEisbaer** [icflorescu/mantine-datatable#471]
**Describe the bug**
Using highlightOnHover with DataTable is not working with mantine 7.2.1

**To Reproduce**
```
// Mantine Table
            <Table highlightOnHover>
                <Table.Thead>
                    <Table.Tr>
                        <Table.Th>Element position</Table.Th>
                        <Table.Th>Element name</Table.Th>
                        <Table.Th>Symbol</Table.Th>
                        <Table.Th>Atomic mass</Table.Th>
                    </Table.Tr>
                </Table.Thead>
                <Table.Tbody>
                    <Table.Tr >
                        <Table.Td>Id</Table.Td>
                        <Table.Td>Name</Table.Td>
                        <Table.Td>Symbol</Table.Td>
                        <Table.Td>Mass</Table.Td>
                    </Table.Tr>
                </Table.Tbody>
            </Table>

// Mantine-DataTable
            <DataTable




                highlightOnHover
                records={[
                    { id: 1, name: 'Joe Biden', bornIn: 1942, party: 'Democratic' },
                    { id: 2, name: 'Donald Trump', bornIn: 1942, party: 'Republican' },
                    { id: 3, name: 'Donald Trump', bornIn: 1942, party: 'Republican' },
                    { id: 4, name: 'Donald Trump', bornIn: 1942, party: 'Republican' },
                    { id: 5, name: 'Donald Trump', bornIn: 1942, party: 'Republican' },
                ]}
                columns={[
                    {
                        accessor: 'id',
                        title: '#',
                        textAlign: 'right'
                    },
                    {
                        accessor: 'name'
                    },
                    {
                        accessor: 'party',
                        // this column has custom cell data rendering
                        render: ({ party }) => (
                            <Box fw={700} c={party === 'Democratic' ? 'blue' : 'red'}>
                                {party.slice(0, 3).toUpperCase()}
                            </Box>
                        ),
                    },
                    { accessor: 'bornIn' },
                ]}
            />
```

**Comment by icflorescu** [comment]
You can check that `highlightOnHover` does work on the documentation website, which is actually a "real" Next.js application that uses the component and the last Mantine version.

For instance, here: https://icflorescu.github.io/mantine-datatable/getting-started/
Or here: https://icflorescu.github.io/mantine-datatable/examples/basic-table-properties/

I've noticed some users tend to gloss over the styling section in the documentation, which can create unexpected issues such as this one.

Are you sure the styles are [applied in the correct order](https://icflorescu.github.io/mantine-datatable/styling/#controlling-the-order-of-styles-with-css-layers)? If they are and you're still facing the issue, can you please provide a reproduction on codesandbox (or something similar)? Thanks!

**Comment by TheEisbaer** [comment]
Hi there,


postcss.config.js:
```
module.exports = {
    plugins: {
        'postcss-import': {},
        'postcss-preset-mantine': {},
        'postcss-simple-vars': {
            variables: {
                'mantine-breakpoint-xs': '36em',
                'mantine-breakpoint-sm': '48em',
                'mantine-breakpoint-md': '62em',
                'mantine-breakpoint-lg': '75em',
                'mantine-breakpoint-xl': '88em',
            },
        },
    },
};
```

layout.tsx:
```
import { AppShell, AppShellMain, AppShellNavbar, ColorSchemeScript, MantineProvider } from '@mantine/core';

import './layout.css';
import CustomAppShellHeader from '@/components/homepage/CustomAppShellHeader';
import MenuAccordion from '@/components/homepage/menuAccordion';


export const metadata = {
  title: 'My Mantine app',
  description: 'I have followed setup instructions carefully',
};



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <AppShell
            header={{ height: 70 }}
            navbar={{
              breakpoint: 'sm', width: 250,
            }}
          >
            <CustomAppShellHeader />
            <AppShellNavbar>
              <MenuAccordion />
            </AppShellNavbar>
            <AppShellMain>{children}</AppShellMain>
          </AppShell>
        </MantineProvider>
      </body>
    </html >
  );
}
```

layout.css
```
/* 👇 Expressly import the mantine core styles into mantine-core layer */
@import '@mantine/core/esm/index.css' layer(mantine-core);

/* 👇 Expressly import the mantine-datatable styles into mantine-datatable layer */
@import 'mantine-datatable/dist/styles.css' layer(mantine-datatable);

/* 👇 Make sure the styles are applied in the correct order */
@layer mantine-core, mantine-datatable;
```

I tripple checked and also tried the other way as described by the instructions, same result

**Comment by TheEisbaer** [comment]
Oh sorry I missed that part with the codesandbox.

will provide one asap

**Comment by TheEisbaer** [comment]
@icflorescu 
Here is the [codesandbox](https://codesandbox.io/p/sandbox/hungry-roentgen-pyd392?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloy5intg000c356lthhbldhb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloy5intg0003356l30qjxvuj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloy5intg0009356lfazto0zv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloy5intg000b356l1kf2pobp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloy5intg0003356l30qjxvuj%2522%253A%257B%2522id%2522%253A%2522cloy5intg0003356l30qjxvuj%2522%252C%2522activeTabId%2522%253A%2522cloy5t7mk02ss356lu3kfmki5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloy5intg0002356lnsx36mdq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cloy5jley00jz356llb0smkj8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Flayout.tsx%2522%252C%2522id%2522%253A%2522cloy5lj4s019h356l5paopgso%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522id%2522%253A%2522cloy5lsa801co356l70mdmv6v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Flayout.css%2522%252C%2522id%2522%253A%2522cloy5njt201tm356l9y877eu0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpostcss.config.js%2522%252C%2522id%2522%253A%2522cloy5nxju01yx356lu9dt7duu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252FFormTable.tsx%2522%252C%2522id%2522%253A%2522cloy5t7mk02ss356lu3kfmki5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cloy5intg000b356l1kf2pobp%2522%253A%257B%2522id%2522%253A%2522cloy5intg000b356l1kf2pobp%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cloy5xqk303tv356l5nol5eiu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cloy5xqk303tv356l5nol5eiu%2522%257D%252C%2522cloy5intg0009356lfazto0zv%2522%253A%257B%2522id%2522%253A%2522cloy5intg0009356lfazto0zv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%252C%2522id%2522%253A%2522cloy5oshp024u356lzamz4gf8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cloy5rv0v02hk356lcpu4t9m9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cloy5rv0v02hk356lcpu4t9m9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by TheEisbaer** [comment]
Nevermind, I got it to work somehow by trying to replicate the issue from scratch.

**Comment by vilola** [comment]
I have similiar issue and I fixed it by importing layer styles 
`import "mantine-datatable/styles.layer.css";`
instead of 
`import "mantine-datatable/styles.css";`

for Mantine, Mantine Datatable and all.

Other styles was fine, just the row highlighting. Do not know why exactly, but it helped.

**Comment by icflorescu** [comment]
@vilola was this comment meant for the current issue or [this new one](https://github.com/icflorescu/mantine-datatable/issues/587)? 🙂

**Comment by vilola** [comment]
@icflorescu no, but probably could be too :D thanks, will link it there.
