### ISSUE TITLE
Visible "no records" statement, even though there are

### ISSUE THREAD

**Issue by baltarifcan** [icflorescu/mantine-datatable#475]
**Describe the bug**
I've tried to start using mantine-datatable with my new project. When I create a datatable with data, and that data is visible in the table, below the table the "no records" statement appears. I've read the documentation to see if I can find something similar but no luck.

**To Reproduce**

1. Create a Vite+React+TypeScript project, installed dependencies
2. Install mantine core and hooks following the mantine's getting started page, create postcss.config.cjs and fill it
3. Install mantine-datatable and clsx with 'pnpm i mantine-datatable clsx'
4. Copy the "Basic usage" examle with companies.json to my project

**Expected behavior**
Since the records are present, the no records text should not be visible

**Screenshots**
![image](https://github.com/icflorescu/mantine-datatable/assets/19823225/b97caa9a-f653-4589-b997-592159851bdc)
![image](https://github.com/icflorescu/mantine-datatable/assets/19823225/12069ccf-b93f-4f51-ac66-fcbec1015beb)

**Desktop (please complete the following information):**

- OS: Windows 11 23H2 Build 22365.2700
- Browser Chrome 
- Version 119.0.6045.160

**Comment by baltarifcan** [comment]
Went through the docs again, missed the styles.layer.css import

**Comment by Sharif-Minhaz** [comment]
> Went through the docs again, missed the styles.layer.css import

After adding `import 'mantine-datatable/styles.layer.css';` Mine worked too.
