### ISSUE TITLE
Package not working with mantine v7.3.0

### ISSUE THREAD

**Issue by lukasbash** [icflorescu/mantine-datatable#484]
**Describe the bug**
Using this table with mantine v7.3.0 causes an unhandled exception with regard to the mantine provider context.

**To Reproduce**
Just use this table with mantine v7.3.0.

**Expected behavior**
No crash.

**Screenshots**
<img width="862" alt="image" src="https://github.com/icflorescu/mantine-datatable/assets/15958032/0a83f773-a64d-4ea2-85d6-8d325251b88a">

**Desktop (please complete the following information):**

- OS: macOS Sonoma
- Browser Chrome
- Version 119.0.6045.199

**Additional context**
The table works really well, but being compatible with at least minor versions of the related component framework is a must in my opinion. Would be sad switching away from this awesome module, but throttling dependency updates is not an option for me 😭

**Comment by isnifer** [comment]
@lukasbash `mantine-datatable` works well with `mantine@7.3.0` — using right now. You have unrelated to to `mantine-datatable` problem on your side.
For example:
<img width="503" alt="image" src="https://github.com/icflorescu/mantine-datatable/assets/1788245/9907b4cc-c2a3-45b9-868a-fdc5f21d0270">

**Comment by lukasbash** [comment]
> @lukasbash `mantine-datatable` works well with `mantine@7.3.0` — using right now. You have unrelated to to `mantine-datatable` problem on your side.
> 
> As I can see your error — you're using `useMantineTheme` in some component that has been rendered outside `<MantineProvider />`. Please, check some modal or something similar that has been rendered outside root (for example in React Portal)
> 
> Since you're using Next.JS — please read carefully all guidelines how to add a `MantineProvider` correctly.
> 
> There is a pinned issue related to you — #451

This is not true, as you can see the lower stack starts from the data table call stack. Neither I am using Next and the mantine provider is the first component after my strict mode:
```
<React.StrictMode>
    <MantineProvider>
    // ...
    </MantineProvider>
</React.StrictMode>
```

Moreover, if I do not change anything but the mantine version, it just works. Only views where data tables are used crash, so I highly doubt it is compatible.

**Comment by isnifer** [comment]
@lukasbash please provide a code example and your file structure. Since I'm using `7.3.0` right now without Next.JS (just Vite+React+React-Router) and everything is working fine.

**Comment by isnifer** [comment]
@lukasbash spent 7 minutes to configure a new `App-directory` based Next.JS app, added `@mantine/core` and `mantine-datatable`:
<img width="556" alt="image" src="https://github.com/icflorescu/mantine-datatable/assets/1788245/4608ce6c-e234-415c-b775-df0e189802fc">

```tsx
"use client";

import { DataTable } from "mantine-datatable";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    import("@mantine/core/package.json").then((json) =>
      console.log("@mantine/core version:", json.version)
    );
    import("mantine-datatable/package.json").then((json) =>
      console.log("mantine-datatable version:", json.version)
    );
    import("next/package.json").then((json) =>
      console.log("next version:", json.version)
    );
  }, []);

  return (
    <DataTable
      striped
      withTableBorder
      withColumnBorders
      highlightOnHover
      minHeight={200}
      idAccessor="name"
      records={[
        { name: "John Doe", manager: "https://google.com" },
        { name: "Jane Doe", manager: "https://google.com" },
        { name: "Jack Doe", manager: "https://google.com" },
      ]}
      columns={[
        { accessor: "name", title: "Name", width: 180 },
        { accessor: "manager", title: "Manager", width: 180 },
      ]}
    />
  );
}
```

```tsx
// layout.tsx
// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import "@mantine/core/styles.css";
import "mantine-datatable/styles.css";

import { MantineProvider, ColorSchemeScript } from "@mantine/core";

export const metadata = {
  title: "My Mantine app",
  description: "I have followed setup instructions carefully",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
```

Everything is working fine.

**Comment by lukasbash** [comment]
I upgraded all my dependencies today and it seems like your table package got one too. Also the matinee dependencies got upgraded and it works now as expected. Still unsure what was the cause ..

> You shouldn't have to, but that's a rather unfair thing to say. Please bear in mind that Mantine DataTable is not a company I or the other code contributors are paid to work for. I do it in my own free time and therefore the project partly depends on the generosity of people who are willing to [sponsor](https://github.com/sponsors/icflorescu) or come up with PRs.

This was for sure not meant to be a biased statement as I really appreciate your work and this package. I know it is hard to get the gap between some package that is actually downloaded and used a lot, but also not profitable for the maintainer.

Thanks a lot for keeping this up!
