### ISSUE TITLE
Set a fixed size for the selection column

### ISSUE THREAD

**Issue by igomest** [icflorescu/mantine-datatable#485]
How can I define a fixed size for the column in which the checkboxes are located?

I have a problem with size inconsistency between browsers. For example, in Chrome, the column sizes are correct.

But if you access Firefox, the size of the record selection column is larger than the others, for example.

Mantine DataTable Version: 7.1.5

**Comment by icflorescu** [comment]
Good catch on Firefox, thanks!

I'll come up with a solution for V7.3, which is due later today and I'll let you know.
