### ISSUE TITLE
onCellDoubleClick and onRowDoubleClick handlers

### ISSUE THREAD

**Issue by lukasbash** [icflorescu/mantine-datatable#492]
**Is your feature request related to a problem? Please describe.**
Using the same approach as e.g. file explorers makes the table more data like.

**Describe the solution you'd like**
Provide handlers for `onCellDoubleClick` and `onRowDoubleClick`.

**Describe alternatives you've considered**
Checking somehow the event details, passed down the normal click handler.

**Additional context**
-

**Comment by icflorescu** [comment]
Just implemented this in the last version, see:
https://icflorescu.github.io/mantine-datatable/examples/handling-row-clicks/#double-clicks
and
https://icflorescu.github.io/mantine-datatable/examples/handling-cell-clicks/#double-clicks
