### ISSUE TITLE
Doesn't disappear 'No records' when have a data

### ISSUE THREAD

**Issue by hitfm00** [icflorescu/mantine-datatable#505]
**Describe the bug**
I have a data from server or from client but this **'No records'** doesn't disappear 

**To Reproduce**
<img width="767" alt="Снимок экрана 2024-01-05 в 03 26 33" src="https://github.com/icflorescu/mantine-datatable/assets/21322208/8567da57-c0da-4105-8483-d04bd8f10250">
Just very light component

**Expected behavior**
Need to disappear 'No records' when have a data

**Screenshots**
<img width="644" alt="Снимок экрана 2024-01-05 в 03 27 49" src="https://github.com/icflorescu/mantine-datatable/assets/21322208/38e090fa-785f-45d7-b478-2c74a74dd6be">

**Desktop (please complete the following information):**

- OS: Macos
- Browser Arc

**Comment by icflorescu** [comment]
Hey, @hitfm00, this can happen if you forgot to import the CSS.
See this discussion in Q&A here: https://github.com/icflorescu/mantine-datatable/discussions/456
And the docs page here: https://icflorescu.github.io/mantine-datatable/styling/

**Comment by icflorescu** [comment]
Hey, @hitfm00, I'm going to close this for now as I suspect it's just a matter of forgetting to import the CSS.
Please feel free to reopen if the problem persists after you've made sure to properly import the styles (see my comment above).

**Comment by hitfm00** [comment]
Hey, @icflorescu, I will check later, thx for the answer
