### ISSUE TITLE
drag and drop with @hello-pangea/dnd

### ISSUE THREAD

**Issue by mehdiraized** [icflorescu/mantine-datatable#513]
mantine has sample for drag and drop rows in table
but we need access to row render for use this package and add this feature
https://ui.mantine.dev/category/dnd/

![image](https://github.com/icflorescu/mantine-datatable/assets/4368004/b86b99de-b970-4b64-936e-40f409bb2199)

**Comment by icflorescu** [comment]
Other users requested the feature too but no one came up with a valid PR so far, and I'm afraid I don't have the luxury of free time at the moment.

**So, I'm 💯 percent open to a PR regarding this!**

**Comment by MohdAhmad1** [comment]
I have created a pr to address this issue, check it here #616  , I just found out that a issue for same already exists

**Comment by icflorescu** [comment]
I'm really curious to see other people's feedback [on the PR](https://github.com/icflorescu/mantine-datatable/pull/616) addressing this issue. My primary concern in regarding the addition of a new mandatory dependency ([Pangea DnD](https://github.com/hello-pangea/dnd)).

**Comment by mehdiraized** [comment]
> I have created a pr to address this issue, check it here #616 , I just found out that a issue for same already exists

can you change your code and create a new page in Examples, if you want to use the Pangea DnD, you can install the package and put the sample code on that page.

**Comment by MohdAhmad1** [comment]
> > I have created a pr to address this issue, check it here #616 , I just found out that a issue for same already exists
> 
> can you change your code and create a new page in Examples, if you want to use the Pangea DnD, you can install the package and put the sample code on that page.

I have already added an example page in /examples/row-dragging/

**Comment by mehdiraized** [comment]
i fixed this issue on this commit
https://github.com/icflorescu/mantine-datatable/pull/621/commits/ee6b61bfb3ac8221b190078ebf4eee808e48312f

**Comment by mehdiraized** [comment]
@icflorescu can you check that PR ?
everything is ok in this PR please check that

**Comment by icflorescu** [comment]
Thanks for the outstanding work, release is on its way to npm registry!
