### ISSUE TITLE
Arrow visible in records per page component

### ISSUE THREAD

**Issue by bastiengrignon** [icflorescu/mantine-datatable#520]
**Describe the bug**

**To Reproduce**

1. Go to [this example](https://icflorescu.github.io/mantine-datatable/examples/pagination/#displaying-a-page-size-selector)
2. Click on 'Records per page selector'
3. Select the first option
4. See the other part of the arrow that should not be visible.

**Expected behavior**
We shouldn't see this part of the arrow
 
**Screenshots**
![Screen at 01-19-2024_14:58:58](https://github.com/icflorescu/mantine-datatable/assets/41306995/8b806e32-88e2-43e7-8756-4b767653723b)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: opera
- Version: 106.0.4998.41

**Comment by icflorescu** [comment]
Well spotted, you must have really good eyesight and attention to details :-)

Looks like this actually comes from Mantine, but it should be fixable with a simple `z-index` patch.

Will fix it in the next version in a couple of days.
Thanks!

**Comment by bastiengrignon** [comment]
Ahah maybe I spent to much time looking at this component while fix other issues :laughing: 

Nice thanks for the information
