### ISSUE TITLE
Storybook: "No records" always show, even with data

### ISSUE THREAD

**Issue by franzos** [icflorescu/mantine-datatable#530]
**Describe the bug**

"No records" should only show, when no data is available (`[]`), but it always shows for me.

**To Reproduce**

1. I initiate with `[]`
2. Set data on initial load

**Expected behavior**

Show "No records", when no records are available.

**Screenshots**

![Screenshot 2024-01-25 at 12-27-14 Components _ FormsTable - Usage ⋅ Storybook](https://github.com/icflorescu/mantine-datatable/assets/2619225/9c4149ae-cee9-4f0d-84b4-ebfb7db0422f)

**Desktop (please complete the following information):**

- OS: Guix
- Browser: Firefox 121.0.1 (64-bit)

```
"@mantine/core": "7.4.2",
"@mantine/form": "^7.4.2",
"@mantine/hooks": "7.4.2",
"mantine-datatable": "^7.4.6",
```

**Additional context**

I initially thought this might be related to styling, but this seems to be alright:

```js
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { Router } from './Router';
import { theme } from './theme';

import '@mantine/core/styles.css';
import '@mantine/core/styles.layer.css';
import 'mantine-datatable/styles.layer.css';
import './assets/layout.css';

export default function App() {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <Router />
        </MantineProvider>
      </body>
    </html>
  );
}
```

Layout:

```css
@layer mantine, mantine-datatable;
```

Here's what my table looks like:

```js
import { useEffect, useState } from 'react';
import { Form } from '@/lib/models';
import { DataTable } from 'mantine-datatable';

export interface FormsTableProps {
  pagination: {
    total: number;
    initial: number;
    perPage: number;
  };
  onChange: (from: number, to: number) => Promise<Form[]>;
}

export function FormsTable(props: FormsTableProps) {
  const [isBusy, setIsBusy] = useState(false);
  const [records, setRecords] = useState<Form[] | []>([]);
  const [page, setPage] = useState(1);

  useEffect(() => {
    const doIt = async () => {
      setIsBusy(true);
      const from = (page - 1) * props.pagination.perPage;
      const to = from + props.pagination.perPage;
      try {
        const records = await props.onChange(from, to);
        setRecords(records);
      } catch (e) {
        console.error(e);
      } finally {
        setIsBusy(false);
      }
    };
    doIt();
  }, [page]);

  const columns = [
    {
      accessor: 'title',
      title: 'Form Name',
    },
    {
      accessor: 'created_at',
      title: 'Created At',
      render: (row: Form) => row.created_at.toLocaleDateString(),
    },
    {
      accessor: 'updated_at',
      title: 'Updated At',
      render: (row: Form) => row.updated_at.toLocaleDateString(),
    },
  ];

  return (
    <>
      <DataTable
        height={300}
        withTableBorder
        records={records}
        columns={columns}
        totalRecords={props.pagination.total}
        recordsPerPage={props.pagination.perPage}
        page={page}
        onPageChange={(p) => setPage(p)}
        fetching={isBusy}
        loadingText="Loading..."
      />
    </>
  );
}
```

I just started playing with Storybook, so this is where I setup the component; I mention this because it might be related though I doubt it.

```js
import { FormsTable } from './Table';
import { forms_placeholder } from '@/lib/story-data';

export default {
  title: 'Components/FormsTable',
};

let perPage = 2;

let pagination = {
  total: forms_placeholder.length,
  initial: 1,
  perPage: perPage,
};

const onChange = async (from: number, to: number) => {
  await new Promise((resolve) => setTimeout(resolve, 1000));
  return forms_placeholder.slice(from, to);
};

export const Usage = () => <FormsTable pagination={pagination} onChange={onChange} />;
```

Also saw this related issue https://github.com/icflorescu/mantine-datatable/issues/505 and discussion here https://github.com/icflorescu/mantine-datatable/discussions/456.

**Comment by icflorescu** [comment]
I'm not sure about Storybook, but I've seen this happening when styles and incorrectly applied.
In your case, it might be because you're importing both the "unlayered" and "layered" version of Mantine core styles:

```ts
import '@mantine/core/styles.css'; // 👈 why?
import '@mantine/core/styles.layer.css';
import 'mantine-datatable/styles.layer.css';
import './assets/layout.css';
```

**Comment by franzos** [comment]
> I'm not sure about Storybook, but I've seen this happening when styles and incorrectly applied. In your case, it might be because you're importing both the "unlayered" and "layered" version of Mantine core styles:
> 
> ```ts
> import '@mantine/core/styles.css'; // 👈 why?
> import '@mantine/core/styles.layer.css';
> import 'mantine-datatable/styles.layer.css';
> import './assets/layout.css';
> ```

I appreciate your help; I'm new to Mantine.

```js
import '@mantine/core/styles.layer.css';
import 'mantine-datatable/styles.layer.css';
import './assets/layout.css';

import { MantineProvider } from '@mantine/core';
import { Router } from './Router';
import { theme } from './theme';

export default function App() {
  return (
    <MantineProvider theme={theme}>
      <Router />
    </MantineProvider>
  );
}
```

I removed the styles, rebuild, reload, but no change.

![Screenshot 2024-01-25 at 14-39-58 Components _ FormsTable - Usage ⋅ Storybook](https://github.com/icflorescu/mantine-datatable/assets/2619225/1f8b2afb-b50e-4e58-95b3-e77cca4271cd)

**Comment by franzos** [comment]
Pushed the code here: `https://github.com/franzos/mantine-datatable-issue-530`

```bash
pnpm install
pnpm run storybook
```

**Comment by icflorescu** [comment]
Believe it or not, but I haven't used Storybook before and I'm not a fan (I hate the amount of boilerplate it comes with, and I've seen it used in many OSS projects - as a replacement for documentation - without adding any real value).

So, I don't really know how a Storybook project should be set up, but I think there's an error in the one you shared: I've noticed that if you're importing the styles:
```ts
import '@mantine/core/styles.css';
import 'mantine-datatable/styles.css';
```
...in your `.storybook/preview.tsx` (instead of `src/App.tsx`), **the error goes away**.

I've made a [PR](https://github.com/franzos/mantine-datatable-issue-530/pull/1/commits/c8cd07c5e49e3b3db2890bebbaac8087a5214682) to your sample repo.

So, since this is obviously a Storybook misconfiguration problem, I'll close the issue here.

**Comment by franzos** [comment]
> I hate the amount of boilerplate it comes with

Yeah, I'm also realizing this; Plus you end up with a lot of callbacks.

I do realize the value; Someone with little experience can easily implement and even test components this way (without bringing up the project, api, ...). Not sure if I will continue to use it personally.

> ...in your .storybook/preview.tsx (instead of src/App.tsx), the error goes away.

Thank you so much!

**Comment by icflorescu** [comment]
No worries :-)
