### ISSUE TITLE
how to use sticky in header table ?

### ISSUE THREAD

**Issue by mehdiraized** [icflorescu/mantine-datatable#542]
i saw this options in documents
```
| 'stickyHeader'
| 'stickyHeaderOffset'
```
we can use this 2 option for make sticky header of rows ?

**Comment by icflorescu** [comment]
I assume you saw those as properties being omitted from the default Mantine table props, because in Mantine DataTable the header is sticky by default when required.
Please refer to the documentation here: https://icflorescu.github.io/mantine-datatable/examples/scrollable-vs-auto-height/

**Comment by mehdiraized** [comment]
I want the 'sticky' feature to not only apply with added height, but also have the table header stick to the top of the page while scrolling the entire page.

**Comment by Strajk** [comment]
@mehdiraized hey, have you find a solution to the whole page scrolling + table header sticky?

**Comment by mehdiraized** [comment]
> @mehdiraized hey, have you find a solution to the whole page scrolling + table header sticky?

no i didn't find any solution of this feature
i haven't time to create new PR for add this feature to mantine-datatable
but next month i can add this feature to repository
