### ISSUE TITLE
Ability to export

### ISSUE THREAD

**Issue by imoby** [icflorescu/mantine-datatable#563]
**Is your feature request related to a problem? Please describe.**
Unable to export data to pdf

**Describe the solution you'd like**
I'd like to be able to export the data in the table. There are a lot of libs like https://www.npmjs.com/package/jspdf that can simplify this

**Describe alternatives you've considered**
Currently have to manage this myself and have to make a separate table using jspdf and it would be nice if it was already integrated

**Additional context**

**Comment by icflorescu** [comment]
Personally, I prefer to use the excellent [ReactPDF](https://react-pdf.org/) by [Diego Muracciole](https://github.com/diegomura) - make sure to check that one out 😉

This is, however, totally out of scope for Mantine DataTable, which - among other things - aims to be a lightweight, dependency-free data table solution tor Mantine applications.

Some users would obviously want to export to PDF, some to Excel, some to CSV, and it would not be possible to accommodate all possible usage scenarios.

I do understand why you'd ideally want a universal silver-bullet solution, but this is definitely something that you'll have to manage yourself 😛

Food for thought: what if you'd need special formatting for the PDF (such as page numbers, headers, footers, etc.)?
