### ISSUE TITLE
[BUG] Maximum update depth exceeded with Mantine 7.7.1

### ISSUE THREAD

**Issue by ebalo55** [icflorescu/mantine-datatable#564]
**Describe the bug**
When running with Next.js 14.1.4 the library cannot be used as the React error `Maximum update depth exceeded` pops out in all pages

**To Reproduce**
I've create a sample bare next+mantine repo [here](https://github.com/ebalo55/mantine-datatable-sample-repo-bug-report)

1. Run the dev server
2. open the browser at `localhost:3000`
3. The error pops out immediately as the home page loads

**Expected behavior**
No error should occur

**Screenshots**
![image](https://github.com/icflorescu/mantine-datatable/assets/12586380/5307ecf3-ec49-4906-9d3b-90a5aad38951)

**Desktop (please complete the following information):**

- OS: Debian Linux
- Browser: Brave (Chromium engine)
- Version: 1.64.109 (chromium 123.0...)

**Comment by ebalo55** [comment]
After a few trials and errors, the problem seems to arise starting at v7.3.0 as up to the release v7.1.7 the error is not thrown

**Comment by FairyPenguin** [comment]
Yeah, I faced this but today with Nextjs 14.1.4 too same error same case. Thanks for reporting this @ebalo55

**Comment by icflorescu** [comment]
I've done some testing and it looks like this has nothing to do with Next.js version, but rather with **the very specific Mantine 7.7.1 version**.

It works fine with Mantine 7.7.0, but fails with Mantine 7.7.1.

I'll investigate it a bit further over the next few days, and raise a [Mantine](https://github.com/mantinedev/mantine) issue if necessary.

@ebalo55, your link leads to a bare Next.js app without Mantine or Mantine DataTable.

@rtivital, apparently something happened between 7.7.0 and 7.7.1 that's causing this. It's kind of difficult to debug, but I'll try to isolate the problem and let you know if I find something.

**Comment by icflorescu** [comment]
I managed to track down the error to Mantine `useLocalStorage`, specifically this change: https://github.com/mantinedev/mantine/pull/5910, which will most likely be fixed in the next release either by https://github.com/mantinedev/mantine/pull/6019 or by https://github.com/mantinedev/mantine/pull/6022.

**Comment by icflorescu** [comment]
Until this is fixed, please refrain from upgrading to Mantine 7.7.1.

**Comment by ebalo55** [comment]
> I've done some testing and it looks like this has nothing to do with Next.js version, but rather with **the very specific Mantine 7.7.1 version**.
> 
> It works fine with Mantine 7.7.0, but fails with Mantine 7.7.1.
> 
> I'll investigate it a bit further over the next few days, and raise a [Mantine](https://github.com/mantinedev/mantine) issue if necessary.
> 
> @ebalo55, your link leads to a bare Next.js app without Mantine or Mantine DataTable.
> 
> @rtivital, apparently something happened between 7.7.0 and 7.7.1 that's causing this. It's kind of difficult to debug, but I'll try to isolate the problem and let you know if I find something.

Ops, leftover push while moving within repos, anyway seems like sticking to 7.7.0 work for now, thank you

**Comment by icflorescu** [comment]
This was fixed in Mantine `v7.7.2`.

**Comment by FairyPenguin** [comment]
> This was fixed in Mantine `v7.7.2`.

Thanks for your effort and update
