### ISSUE TITLE
seeing a console error when I modify the paginationText in pagination

### ISSUE THREAD

**Issue by dinesh5k** [icflorescu/mantine-datatable#570]
**Describe the bug**
Added a select in paginationText of the data table and seeing a console error: 

validateDOMNesting(...): <div> cannot appear as a descendant of <p>, with noway to fix the error.

1. create a manatine datatable grid
2. in the paginationText return this
```javascript
<span>
            Records {from} - {to} of {totalRecords}
          </span>
          <Select 
placeholder='Page'
            data={['1', '2']}
``` >

4. you will See error in console.

**Expected behavior**
expecting the pagination text to be a div or at least give an option to declare what element it should be so I can avoid this error.

like if I can say, for record text, i want to use div tag instead of p tag.

![Screenshot 2024-04-11 at 10 25 29 PM](https://github.com/icflorescu/mantine-datatable/assets/3596902/38be0ff3-aad6-457a-a0a3-dc7e237af532)
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. iOS]
- Browser [e.g. chrome, safari]
- Version [e.g. 22]

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]
- OS: [e.g. iOS8.1]
- Browser [e.g. stock browser, safari]
- Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by icflorescu** [comment]
Hey @dinesh5k, thanks for bringing this to my attention.
In `v7.8.1`, I have updated all internal `Text` components to output divs instead of paragraphs to avoid issues such as this one.
Related to your specific usage scenario, there is however a better way to display a page size selector, as depicted in the docs here: https://icflorescu.github.io/mantine-datatable/examples/pagination/#displaying-a-page-size-selector

**Comment by dinesh5k** [comment]
Thanks for getting back to me, my need to create a select that will let the user jump to any page he wants to in the pagination list, so I added a select with all the available list of pages and letting user to jump to a particular page, any suggestion how to implement this?
