### ISSUE TITLE
Can't make highlightOnHover work ?

### ISSUE THREAD

**Issue by laugri** [icflorescu/mantine-datatable#587]
**Describe the bug**
I have a Nextjs application using Mantine. I just tried `mantine-datatable` but can't make the highlight in hover option work.

**To Reproduce**

I tried using a very basic table  from the examples in my app:

```tsx
export default function SubstituteOptionsTable({
  substituteOptions,
  eventForSubstitution,
}: {
  substituteOptions: SubstituteOptions;
  eventForSubstitution: CalendarEventIncludingAll;
}) {
  return (
    <DataTable
      columns={[{ accessor: 'name' }, { accessor: 'streetAddress' }, { accessor: 'city' }, { accessor: 'state' }]}
      highlightOnHover
      records={[
        {
          "id": "1323addd-a4ac-4dd2-8de2-6f934969a0f1",
          "name": "Feest, Bogan and Herzog",
          "streetAddress": "21716 Ratke Drive",
          "city": "Stromanport",
          "state": "WY",
          "missionStatement": "Innovate bricks-and-clicks metrics."
        },
        {
          "id": "0cf96f1c-62c9-4e3f-97b0-4a2e8fa2bf6b",
          "name": "Cummerata - Kuhlman",
          "streetAddress": "6389 Dicki Stream",
          "city": "South Gate",
          "state": "NH",
          "missionStatement": "Harness real-time channels."
        }]}
    />
  );
}
```

I paid attention to import the css too in `layout.tsx`:

```tsx
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/spotlight/styles.css';
import 'mantine-datatable/styles.layer.css';
import 'react-big-calendar/lib/css/react-big-calendar.css';

import React from 'react';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import { resolver, theme } from './theme';

export const metadata = {
  title: 'Bloom Care',
  description: 'The AI copilot for homecare',
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.png" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <MantineProvider theme={theme} cssVariablesResolver={resolver}>
          <Notifications position="top-center" />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
```

I can't find what I could be doing wrong since I have done so few. I checked the doc multiple times. Is there anything I forgot?

**Expected behavior**
Having the option work.

**Desktop (please complete the following information):**

- OS: MacOs 12.7.4
- Browser Chrome Version 124.0.6367.61

**Comment by laugri** [comment]
I think it is a new issue with `nextjs` css chunking as I am getting 404 errors around this when in `next dev`. I'll investigate further:

```
GET /_next/static/css/app/react-big-calendar.css.map 404 in 12451ms
 GET /_next/static/chunks/app/(auth)/planning/YearsList.module.css.mjs.map 404 in 6085ms
 GET /_next/static/chunks/app/(auth)/Spotlight.module.css.mjs.map 404 in 11766ms
 GET /_next/static/chunks/app/Notifications.module.css.mjs.map 404 in 12090ms
 ```

**Comment by laugri** [comment]
I downgraded to next 14.1.3, the 404 are gone but I still don't have the highlights working 🤔 .

**Comment by icflorescu** [comment]
The [documentation website](https://icflorescu.github.io/mantine-datatable/) itself is built on Next.js; I just bumped it to the latest version (`14.2.3` at the moment) and there are no issues with it, as you can see.

Related to your `highlightOnHover` problem, perhaps it happens because you're importing the **non-layered** CSS version of Mantine packages and the **layered** CSS version for Mantine DataTable?

Either try with:

```ts
import '@mantine/core/styles.layer.css';
import '@mantine/dates/styles.layer.css';
import '@mantine/notifications/styles.layer.css';
import '@mantine/spotlight/styles.layer.css';
import 'mantine-datatable/styles.layer.css';
```
...or:
```ts
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/spotlight/styles.css';
import 'mantine-datatable/styles.css';
```
...but do **not** mix them.

Let me know how it goes.

**Comment by icflorescu** [comment]
@laugri if you're importing the **layered** styles, make sure to also enforce their order, as explained in the [styling docs page here](https://icflorescu.github.io/mantine-datatable/styling/#controlling-the-order-of-styles-with-css-layers).

Since this is something that periodically confuses people and generates issues and discussions from time to time, I'm 100% open to suggestions on how I could improve the docs. I'd like to hear your thoughts on this, @laugri and @vilola.

**Comment by laugri** [comment]
@icflorescu thanks for the prompt answer. Mixing layered and non-layered was the issue. My bad.

I should have payed more attention to the styling page. I can try to describe what made me not look correctly:

- I had seen the Getting Started warning ("Very important The @mantine/core package styles must be applied before Mantine DataTable styles.).
- Because I am not familiar with CSS layers, I didn't catch that the imports in the first examples use them.
- For some reasons, on the styling page, I assumed the CSS layers part was another possible approach, not a mandatory part, and I ignored it.
- When skimming through the page, I thought "well I am already using Mantine v7 so this difference stuff isn't for me".

Some ideas:

- Maybe you could make the differences from v6 to v7 less prominent, in favor of just showing what needs to be done ?
- Maybe merge the styling page into Getting Started so that it is unquestionably part of the setup.

Sorry if I am not being super helpful here, looking back there already were many warnings I ignored 🤷 .
