### ISSUE TITLE
DataTable component ignores withRowBorders=false property on the last row

### ISSUE THREAD

**Issue by khashashin** [icflorescu/mantine-datatable#588]
**Description:**
The DataTable component continues to render a border on the last row despite the withRowBorders property being set to false. This unexpected behavior causes UI inconsistency.

**To Reproduce**
[Steps to reproduce the behavior:](https://stackblitz.com/edit/vitejs-vite-dzsrrb?file=src%2Fmain.jsx)

**Expected behavior**
I expect that when withRowBorders is set to false, no rows should display borders, including the last row in the table.

**Screenshots**
![image](https://github.com/icflorescu/mantine-datatable/assets/17837758/605d6832-73e2-45da-bbd3-1dcc4ea3634f)

**Comment by khashashin** [comment]
I tested the "native" mantine table, it does not apply the border to the last element when withRowBorders is set to false

**Comment by icflorescu** [comment]
Fixed in `v7.9.1`.
