### ISSUE TITLE
No records is always shown, even with data loaded

### ISSUE THREAD

**Issue by tbowmo** [icflorescu/mantine-datatable#591]
**Describe the bug**
I'm trying to use mantine-datatable@7.9.1, and implementing a dead simple table like the following

```js
import { DataTable } from 'mantine-datatable';

export function HomePage() {
  return (
    <DataTable
      columns={[
      { accessor: 'name' },
      { accessor: 'email' },
    ]}
      records={[
      { name: 'test', email: 'no@where.net' },
      { name: 'john doe', email: 'joh@doe.net' },
    ]}
  />);
}
```
It always show the message "No records", even with data loaded (like above example).

**To Reproduce**

Create a simple mantine starter project, and add the above code sample to a component

**Expected behavior**
I would expect that the "No records" message would not be displayed when data is actually loaded.

**Screenshots**
![image](https://github.com/icflorescu/mantine-datatable/assets/5305197/fef3b43d-d3d8-4f23-83ac-2dd81bbb35b8)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome and Firefox
- Versions: Chrome 124.0.6367.201, FireFox 125.0

**Comment by icflorescu** [comment]
Hey @tbowmo, this only happens when styles are [not imported or applied properly](https://icflorescu.github.io/mantine-datatable/styling/).
If you can share your setup in a codesandbox or something similar, I might be able to help you.

**Comment by tbowmo** [comment]
That was it, I did not import styles from mantine-datatables.. After doing that, it disappears :)

Thanks for the quick help

**Comment by icflorescu** [comment]
No worries.
