### ISSUE TITLE
Cursor : pointer not showing when using onRowClick

### ISSUE THREAD

**Issue by darwinhace** [icflorescu/mantine-datatable#593]
**Describe the bug**
Datatable component not showing the pointer when using `onRowClick` function

**To Reproduce**
[https://icflorescu.github.io/mantine-datatable/examples/handling-row-clicks/](url)

**Expected behavior**
`Cursor: pointer` will show when using `onRowClick` function

**Screenshots**
![image](https://github.com/icflorescu/mantine-datatable/assets/76155308/62796699-05ba-4a1b-a023-946d857c4bd3)

**Comment by icflorescu** [comment]
Thanks for the heads-up. This will be fixed in the next version.
