### ISSUE TITLE
tabel last row

### ISSUE THREAD

**Issue by Number5768** [icflorescu/mantine-datatable#599]
![1](https://github.com/icflorescu/mantine-datatable/assets/52844429/605091b5-f404-4ef0-9d85-2232c3994d80)
![2](https://github.com/icflorescu/mantine-datatable/assets/52844429/2b46e387-f434-4491-98c7-6e3982446ced)

Is this normal?
Not equal
I covered it with red as in picture 1 and picture 2.

**Comment by icflorescu** [comment]
Each `<td />` has a bottom border except the ones on the last row, hence the `1px` difference.
