### ISSUE TITLE
Expanding rows behavior

### ISSUE THREAD

**Issue by lurepos** [icflorescu/mantine-datatable#609]
**Describe the bug**
IDK why my Next project turned into this bug, but the expanding rows official example it's expanding/collapsing all rows at same time, I had it working properly before but now it fails like this.

**Expected behavior**
Expand a row at once.

**Screenshots**
http://i.imgur.com/pPLeGvP.mp4

**Desktop (please complete the following information):**

- OS: Running on dockerized Debian
- Browser Brave and Firefox
- Version `"mantine-datatable": "^7.8.1"`

**Comment by mikkurogue** [comment]
Do you have an index column to use? I remember having a similar issue at work and it turned out that it would need a unique index per row to handle the row expansion

for context we define the `idAccessor` prop to be the id accessor. And in the `rowExpansion` callback we define the `content` function with the record and its index. IF we did not provide an idAccessor then it would open all rows

**Comment by mikkurogue** [comment]
hey @lfsaga 
What you could do, is in your column definition create a hidden column that could be a combination of whatever 2 fields you want.


Something like this:

```ts
// Column definition
const cols = [
  {
    accessor: 'unique_row_id',
    hidden: true
  },
  {
    accessor: 'column_1',
    title: 'Column 1',
  }
]
```

and wherever you create your records array, you then have to create the composition value.

```ts
 // data response from api as example
 const dataFromApi = [
    {
      slug: 'route_slug',
      version: 'v1',
      column_1: 'Route slug v1'
    },
    {
      slug: 'route_slug',
      version: 'v2',
      column_1: 'Route slug v2'
    }
  ]

  const records = dataFromApi.map((item) => {
    return {
      unique_row_id: `${item.slug}_${item.version}`, // note the composition here
      column_1: item.column_1
    }
  })```

As long as the combination of `${item.slug}_${item.version}` is always unique you should be fine. If this is not the case, I'd then recommend explicitly defining an index column in the same way and populating this from the `Array.map(cb(element, index)` index and making sure indexes never overlap on the parent

**Comment by mikkurogue** [comment]
Nice, cool stuff! Glad to be of service
