### ISSUE TITLE
Pagination Shows "..." if fetching is true but there is pagination data provided

### ISSUE THREAD

**Issue by mgreenw** [icflorescu/mantine-datatable#614]
**Describe the bug**
If there is pagination data provided (`totalRecords`, `recordsPerPage`, and `page`) but `fetching` is `true`, I expect the pagination fields to continue rendering normally while the rest of the data in the table shows a loading spinner. The use case is that it should be possible to fetch the pagination data and the actual data separately so there is no unexpected "..." while I'm fetching a new page of data

**To Reproduce**

1. In the async loading example, separate out the data fetching from the "pagination info" fetching (e.g. the total number of results in the set). Fetching the pagination info should not require the page or page size as input, and thus the data doesn't change when you change pages
2. Use the pagination info to supply `totalRecords`, `recordsPerPage`, and `page`
3. When the page changes and `fetching: true`, the pagination turns into `...`, even though the three above fields are properly set

**Expected behavior**
I expect to see the pagination fields whenever `totalRecords`, `recordsPerPage`, and `page` are set.

**Screenshots**
<img width="947" alt="Screenshot 2024-07-01 at 5 40 10 PM" src="https://github.com/icflorescu/mantine-datatable/assets/2615374/512e0c18-ec08-4223-8d29-bb4a8c3e34fe">

**Desktop (please complete the following information):**

- OS: macOS
- Browser Firefox
- Version 127

**Comment by candogusyilmaz** [comment]
I'm experiencing this issue after i updated all of the npm packages which had mantine-datatable aswell. I believe it doesn't update the totalRecords when changed. It happens when totalRecords is undefined in my scenario.
