### ISSUE TITLE
Change Page Size (onRecordsPerPageChange)

### ISSUE THREAD

**Issue by mgreenw** [icflorescu/mantine-datatable#615]
**Describe the solution you'd like**
Similar to `onPageChange`, it would be awesome if it were possible to update the number of records per page by supplying a `onRecordsPerPageChange` param that was called when you update the records per page. This would most likely be a <Select> with default options of 10, 20, 50, and 100 (customizable via other props).

**Describe alternatives you've considered**
- Using `paginationText` to render a <Select> component to handle this myself

**Additional context**
See https://ant.design/components/pagination#components-pagination-demo-changer for an example.

**Comment by muhammedaksam** [comment]
> **Describe the solution you'd like** Similar to `onPageChange`, it would be awesome if it were possible to update the number of records per page by supplying a `onRecordsPerPageChange` param that was called when you update the records per page. This would most likely be a with default options of 10, 20, 50, and 100 (customizable via other props). Describe alternatives you've considered Using paginationText to render a component to handle this myself
> 
> **Additional context** See https://ant.design/components/pagination#components-pagination-demo-changer for an example.

Isn't `onRecordsPerPageChange` already exist on https://icflorescu.github.io/mantine-datatable/examples/pagination/#displaying-a-page-size-selector or am I missing something?

**Comment by mgreenw** [comment]
Oi, missed that in the docs. Thanks!
