### ISSUE TITLE
MantineProvider not found and this really only Next.js?

### ISSUE THREAD

**Issue by AddictArts** [icflorescu/mantine-datatable#617]
A non Next.js app, just vite, the app is working with Mantine controls, v7. However, when adding the data table I get `MantineProvider not found`.

Reproduce:
Use the component outside Next.js.

It would be nice to have a working example that is not next.js. Thanks in advance.

**Comment by AddictArts** [comment]
I was able to solve this for now by deleting the `.vite` directory prior to launch. This appears to be debug / dev only.

**Comment by icflorescu** [comment]
Yes, `.vite` and `.next` caches can create such problems sometimes.
AFAIK, lots of people are using `Mantine DataTable` in Vite and/or Remix apps.

**Comment by AddictArts** [comment]
Thanks @icflorescu for reference to anyone who comes to this, I was also using `deno` with something like `deno task npm:vite`.
