### ISSUE TITLE
Clarify how one could combine the row expansion behaviour with row actions

### ISSUE THREAD

**Issue by icflorescu** [icflorescu/mantine-datatable#62]
As mentioned [here](https://github.com/icflorescu/mantine-datatable/discussions/28#discussioncomment-3734671).

**Comment by otobot1** [comment]
I like theexample. I feel like it should be on the `row-actions-cell` example page though. The example is showing a modification of that behaviour, not of the expanded row. Also, it's an important example that could be a real "gotcha" if people are using both features and only skim the documentation, so having it somewhere more prominent would be ideal I think.
