### ISSUE TITLE
Multselect in filter closes filter automatically

### ISSUE THREAD

**Issue by NotNullDev** [icflorescu/mantine-datatable#620]
**Describe the bug**
As in description

**To Reproduce**
Go to the examples: https://icflorescu.github.io/mantine-datatable/examples/searching-and-filtering.
Filter by departament name.
Filter will be closed automatically after selection of just 1 element.

**Expected behavior**
User should be able to select multiple element in the multiselect input before applying the filter.

I would expect multiselect to work in the same way as range calendar, also from the example above (maybe additional button "apply" should be required to close the filter).

When you click in the example on "clear filter" button in the multiselect it's not closing automatically, so it's inconsistent as well.

Shouldn't it work like "agent" filter from the follwing example?
https://primeng.org/table#customers

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Brave
- Version 1.66.113 Chromium: 125.0.6422.76 (Official Build) (64-bit)

**Additional context**

**Comment by NotNullDev** [comment]
I found the solution in the mantine popovers documentation.

```typescript
    {
                            accessor: 'status',
                            filter: ({ close }) => <MultiSelect
                              width={120}
                              data={['haha', 'hehe']}
                              comboboxProps={{ withinPortal: false }}
                              placeholder="Search departments…"
                              leftSection={<IconSearch size={16} />}
                            />,
     },
``` 

by adding
```typescript
comboboxProps={{ withinPortal: false }}
```

Multiselect no longer closes on the option selection.

**Comment by mzdr** [comment]
@NotNullDev I was just about to open another issue, reporting exactly the same thing as you did. But then I saw your solution to the problem, thank you for posting it, really appreciate it.

@icflorescu I think it might be worth mentioning this in the documentation/website, because currently this phenomenon can be experienced on the example page as well.

https://github.com/user-attachments/assets/c8b2e87d-ac4c-4fc7-9269-318b7cfda336
