### ISSUE TITLE
mantine version 7 spoiler is not working correctly in mantine-datatable version7

### ISSUE THREAD

**Issue by sumancrest0001** [icflorescu/mantine-datatable#628]
**Describe the bug**
I wanted to build a table in which each row will contain a show more button. when clicked all the hidden content of that row will be shown. I am using the mantine spoiler component to show and hide content. When I use the spoiler component in rows, it will start to jump and continuously switch between expanded and collapsed states. I tried it with a button that will change the height of the rows but I am facing the same issue. it will expand for a brief moment and again go back to the collapsed state.

**To Reproduce**
use mantine-datatable with mantine spoiler component inside a row that will hide and show certain content of the row.

**Expected behavior**
it is supposed to hide and show content. Same as how spoiler works on normal pages.

**Screenshots**
it was continuously fluctuating between expanded and shrink states. So, hard to take screenshot.

**Desktop (please complete the following information):**

UPDATE: upon investigating more I found that mantine spoiler is not working correctly in mantine-datatable version 7.

- OS: [ubuntu and mac]
- Browser [chrome]
- Version [ubuntu 20]

**Comment by icflorescu** [comment]
You should use the [row expansion feature](https://icflorescu.github.io/mantine-datatable/examples/expanding-rows/) to implement this behavior.
