### ISSUE TITLE
Overriding popover props for filters

### ISSUE THREAD

**Issue by yverby** [icflorescu/mantine-datatable#645]
I have a problem with the filters popover, when the table has a large number of columns, and one of the filters is open when scrolling the table than the popover destroys the layout page, an additional scroll appears on the page.

Example: https://stackblitz.com/edit/github-wjvkrc-jv7dj5
Select the last filter and scroll the table content to the left, pay your attention to the additional horizontal scrolling of the page.

Example from docs:
<img width="402" alt="portal" src="https://github.com/user-attachments/assets/644097f8-7f91-43a8-88c7-e328463562b5">

The reason for this is that `Popover` component that is used in `DataTableHeaderCellFilter` component has `withinPortal={true}` prop by default. By changing this prop to `false`, the popover behavior looks better.

Example from docs:
<img width="402" alt="inside" src="https://github.com/user-attachments/assets/d3acdc9f-e601-4063-9c7f-5d137c18fee7">

Would it be a good idea to add the ability to override `Popover` component props for the filters, or is there a possible workaround?

**Comment by jviets** [comment]
+1: I have the problem that I render that table in a shadow component of a custom html element (micro frontend). I have to pass the @mantine/dates-styles to the parent app, because the popover is in the portal....

**Comment by icflorescu** [comment]
This will be fixed in the new version that will be released later today; a new `filterPopoverProps` will be added, allowing you to override the default behaviour.

**Comment by jviets** [comment]
Thank you very much :) Could you now please still remove the console debug logs?

<img width="498" alt="grafik" src="https://github.com/user-attachments/assets/9153240b-4ede-444e-aa0f-288452cc3d8e">

**Comment by icflorescu** [comment]
Done, `7.14.5` is on the way.

**Comment by jadamita** [comment]
@icflorescu 
The changes here: https://github.com/icflorescu/mantine-datatable/pull/671/commits/0d0bd0af4c9239236d81cc7852952738f03a0606#diff-3db3c9daa1bca0ac90cd4e76803db597a7bbada9dfc43f5103e9276822d7f3f6

appears to break the filter component content when used inside web-component's shadowDom.

no matter where you click inside the popover, it will always close the popover. This makes it so the user is unable to click on any control (textinput, datepicker, etc) without closing the filter popover. I have tried using these new props. but anywhere I click, closes it.

**Comment by jadamita** [comment]
Another idea would be to have a prop that disables the code here:
https://github.com/icflorescu/mantine-datatable/blob/e38290d1813b69404fe5bf8f22602e894be2aeb6/package/DataTableHeaderCellFilter.tsx#L20
