### ISSUE TITLE
Filter popup not closing after clicking outside

### ISSUE THREAD

**Issue by mmuejde** [icflorescu/mantine-datatable#659]
When using the filter feature within the application, there is an issue where the filter popup does not close when the user clicks outside of it. 

Deps:
- "@mantine/core": "^7.13.3"
- "mantine-datatable": "^7.12.4"
- Safari Version 18.0.1 (20619.1.26.31.7)
- Firefox Developer 132.0b9 (aarch64)

![CleanShot 2024-10-22 at 11 13 18@2x](https://github.com/user-attachments/assets/d973ebb1-074d-443c-9fd9-49854251af1b)

**Comment by mmuejde** [comment]
See https://github.com/mantinedev/mantine/issues/7000

**Comment by samjegal** [comment]
This is reproduced again in v7.14.1.

**Comment by alimehasin** [comment]
> This is reproduced again in v7.14.1.

Yes, I am facing the same issue, I am using `v7.14.1`

**Comment by samjegal** [comment]
Also appears in v7.14.2. I think we should reopen the issue.

**Comment by icflorescu** [comment]
I'll add a fix not relying on default Mantine behaviour in the new release later today.

**Comment by samjegal** [comment]
Thank you. The issue has been resolved.

**Comment by samjegal** [comment]
@icflorescu Thank you. The issue has been resolved.

**Comment by jadamita** [comment]
This breaks filter popovers for applications that use web-components in the shadow DOM. It would be ideal if we could have a prop that disables this feature. This would let the user handle the closing themselves.
