### ISSUE TITLE
Wrong module file extension in package.json

### ISSUE THREAD

**Issue by youssefhabri** [icflorescu/mantine-datatable#7]
**Describe the bug**
In `package.js`, the module is defined as `"module": "dist/index.ejs"`, but the `build.mjs` generates a file with  the `mjs` extension.

**Expected behavior**
`package.json` should be switch to use `index.mjs`

**Screenshots**

**Additional context**
I discovered this issue while using the package with Vite, and Vite complained about an incorrect module export, and indeed it was point to a non-existing file.

**Comment by icflorescu** [comment]
Good catch, thank you!
Will fix it tomorrow and let you know when it's released.

**Comment by icflorescu** [comment]
The fix should now be released in `v.1.0.8`.
Please let me know if you encounter any issues in your Vite setup due to `lodash` peer dep. Some people [said it might happen](https://github.com/icflorescu/mantine-datatable/issues/3).
Thanks again.

**Comment by youssefhabri** [comment]
Thanks for the quick fix. Will let you know if I encounter anything :)
