### ISSUE TITLE
Expanded rows should be controllable

### ISSUE THREAD

**Issue by icflorescu** [icflorescu/mantine-datatable#73]
As requested [here](https://github.com/icflorescu/mantine-datatable/discussions/72).

Gist:

The `rowExpansion` property object should also include:
- `records` → currently expanded records
- `onChange` → callback fired when currently expanded records change: `onChange: (records: T[]) => void`

**Comment by otobot1** [comment]
@icflorescu Have you had a chance to work on this issue yet? I can take a crack at it if you haven't.

**Comment by icflorescu** [comment]
@otobot1 Not yet, but I will over the weekend.

**Comment by icflorescu** [comment]
Done in `v1.7.9`. Can be used like this:

```ts
<DataTable
  // ...
  rowExpansion={{
    // ...
    expanded: {
      recordIds: expandedRecordIds,
      onRecordIdsChange: setExpandedRecordIds,
    },
  }}
/>
```

Full working example in **Controlled mode** section of [this page](https://icflorescu.github.io/mantine-datatable/examples/expanding-rows).

**Comment by icflorescu** [comment]
@otobot1 if you're curious, this is handled mostly in the [`useRowExpansion` hook here](https://github.com/icflorescu/mantine-datatable/blob/897b4c724b6755126c57e50b8374f20eb9fa940a/package/hooks.ts#L62).

**Comment by otobot1** [comment]
> @otobot1 if you're curious, this is handled mostly in the [`useRowExpansion` hook here](https://github.com/icflorescu/mantine-datatable/blob/897b4c724b6755126c57e50b8374f20eb9fa940a/package/hooks.ts#L62).

I'll check it out!
