### ISSUE TITLE
Frozen/Fixed Columns

### ISSUE THREAD

**Issue by serhanekicii** [icflorescu/mantine-datatable#78]
Highly demanded feature and already persist on popular similar projects.

**Comment by icflorescu** [comment]
Not exactly a breeze to implement, though.
Feel free to come up with a PR if you have an idea on how this could be done without breaking existing functionality.

**Comment by icflorescu** [comment]
@KaptinLin & @serhanekicii if you have an idea on how this could be implemented, by all means, feel free to come up with a PR 🙏

**Comment by icflorescu** [comment]
I'll close this as "not planned" for now. Please feel free to reopen if you have an idea of how this could be done without breaking existing functionality.
