### ISSUE TITLE
Column titleClassName support

### ISSUE THREAD

**Issue by KaptinLin** [icflorescu/mantine-datatable#80]
**Is your feature request related to a problem? Please describe.**
We can styling column cells, but we can't styling column header/title cells.

**Describe the solution you'd like**
We can do the same like `cellsClassName`, `cellsStyle`
```
      columns={[
        {
          // style title with a class name
          titleClassName: classes.idColumnTitle,
          // style header with a CSS properties object
          titleStyle: {
            fontStyle: 'italic',
          },
        },
        ...
      ]}
```

**Comment by icflorescu** [comment]
Available as soon as `v1.7.7` hits the `npm` registry.
