### ISSUE TITLE
rowExpansion bug: All rows expand

### ISSUE THREAD

**Issue by ndanny** [icflorescu/mantine-datatable#90]
**Describe the bug**
In the `rowExpansion` feature...

If any/all records have a field name that starts with a capital letter, clicking on any row causes all rows to expand.

For instance:
`const rows = [{ID: 123, "First Name": "Danny"}, {ID: 789, "First Name": "Eiter"}]` causes all records to expand instead of the single row the user clicks.

A temporary workaround is to do the following:
`const rows = [{id: 123, firstName: "Danny"}, {id: 789, firstName: "Eiter"}]` 

**To Reproduce**
1. Create a DataTable using the rows example I showed above.
2. In the UI, expand the first row.
3. All rows will expand.

**Expected behavior**
Only one row should expand.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**
TypeScript, NextJS

**Comment by icflorescu** [comment]
That's awkward :-)
Well spotted, thanks.
Will have a look and let you know as soon as it's fixed.

**Comment by icflorescu** [comment]
Your example almost got me fooled as well, but no, it's actually not a bug. and has nothing to do with capital letter columns.

It's easy to miss, but if you're using `const rows = [{ID: 123, "First Name": "Danny"}, {ID: 789, "First Name": "Eiter"}]` as a data source, it means you have a [non-standard record id](https://icflorescu.github.io/mantine-datatable/examples/non-standard-record-ids). The default `idAccessor` is `'id'`, and `'ID' !== 'id'`.

So, if you want to keep your data source as it is, set the DataTable `idAccessor` to `'ID'` like so:

```ts
<DataTable
  columns={[{ accessor: 'ID' }, { accessor: 'First Name' }]}
  records={[
    { ID: 123, 'First Name': 'Danny' },
    { ID: 789, 'First Name': 'Eiter' },
  ]}
  idAccessor="ID" // 👉 because 'ID' !== 'id'
  rowExpansion={{ content: () => <Box p="lg">Expanded</Box> }}
/>
```
