### ISSUE TITLE
Pagination bar not responsive friendly and disappeared in horizontal scroll  

### ISSUE THREAD

**Issue by roychung96** [icflorescu/mantine-datatable#98]
**Describe the bug**
The pagination bar is not sticky and adjust to screen width when added more column added /  screen size change and horizontal scroll shown.
![image](https://user-images.githubusercontent.com/17947488/196631812-e492221a-cdb0-4dde-9f19-8c1115289c74.png)
needed to do horizontal scroll  to the end of the table
![image](https://user-images.githubusercontent.com/17947488/196629580-37256c34-f261-45b3-984a-b7c5241beace.png)

**To Reproduce**
1. Zoom out the screen/ add more column to datatable to make it horizontal scroll 

**Expected behavior**
Should be like this, the pagination bar is not effect by the screen size and column count
![image](https://user-images.githubusercontent.com/17947488/196631251-ed9e5130-c7e7-436d-a7e4-9e68d6889542.png)

**Comment by icflorescu** [comment]
The pagination footer **is** responsive in the sense that it wraps on screens wider than `xs`.
Look at both these examples:

- [Pagination](https://icflorescu.github.io/mantine-datatable/examples/pagination)
- [Complex usage](https://icflorescu.github.io/mantine-datatable/examples/complex-usage)

Resize the window or use a mobile phone and you should see something like this:

![image](https://user-images.githubusercontent.com/581999/196714859-e9019b89-3666-4287-8400-1b2404063900.png)

Perhaps you can share a working example reproducing your specific use-case? (i.e. codesandbox)

**Comment by roychung96** [comment]
when more column are added you will see the bug
in mobile need to horizontal scroll to see pagination controls 
![image](https://user-images.githubusercontent.com/17947488/196850735-13811fce-402d-483d-950d-ff711e5a4965.png)
in desktop view 
![image](https://user-images.githubusercontent.com/17947488/196850929-018b699e-81b5-4c5a-b516-09f55c745c62.png)

**Comment by roychung96** [comment]
I warped the datatable in Mantine ScrollArea for horizontal scrolling when more columns are added
![image](https://user-images.githubusercontent.com/17947488/196851262-b0e08a8c-4fbe-44a5-8cf1-de4a516b2948.png)

**Comment by icflorescu** [comment]
Ah, I suspected that much.
Never wrap the DataTable in a ScrollArea.
It's completely unnecessary and can lead to unexpected results (as you see), because the DataTable has its own internal ScrollArea and it's horizontally-scrollable by default, as you can see in the docs website example pages.

**Comment by StringKe** [comment]
@icflorescu How do I turn on horizontal scrolling?

**Comment by icflorescu** [comment]
@StringKe See the docs here: https://icflorescu.github.io/mantine-datatable/examples/scrollable-vs-auto-height

> The `DataTable` will always be “horizontally-scrollable” if its width it greater than its container width.

You don't have to do anything specifically to turn on horizontal scrolling.
